### ISSUE TITLE
Bottom Navigation issues

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-attendee-android#1139]
- [ ] Each time I go to events section, it is reloading
- [ ] Each time I go to Tickets section, it is reloading

This should not happen

**Comment by liveHarshit** [comment]
Issue #1078 for events section.

**Comment by angmas1** [comment]
Can I work on this?

**Comment by anhanh11001** [comment]
@iamareebjamal @liveHarshit I have investigated this issue over the last 2 days. For my own knowledge now, it's clueless for me to fix this issue.

So basically the problem I found is that in the MainActivity, we set up the bottom navigation with navController:
`setupWithNavController(navigation, navController)`
From what I understand, everytime we click on a bottom navigation's icon, the navController will use the method navigate() to change the fragment in the container, and then clear(pop) all the fragment in the backstack. So if we use navigation with navController here, I don't find a way to keep all the old fragments.

I have tried to research on Singleton pattern to make each fragment a single instance, but I didn't find anything helpful. I also tried to save old fragments by using supportFragmentManager to save the fragment with tag but it made the code really complex and it would take a lot of time to refractor.

Please give some advices or correct me if something is not right

**Comment by liveHarshit** [comment]
> So basically the problem I found is that in the MainActivity, we set up the bottom navigation with navController:
> `setupWithNavController(navigation, navController)`
> From what I understand, everytime we click on a bottom navigation's icon, the navController will use the method navigate() to change the fragment in the container, and then clear(pop) all the fragment in the backstack. So if we use navigation with navController here, I don't find a way to keep all the old fragment

Please read comments in issue #1078. It is already discussed.

**Comment by liveHarshit** [comment]
> I also tried to save old fragments by using supportFragmentManager to save the fragment

It was used earlier, but now we want to do it with navigation architecture component. 
You can see the method in utils for check and load fragment. It is still there.

**Comment by anhanh11001** [comment]
is anyone working on these issues? Can I work on this?

**Comment by sdew021** [comment]
hey @iamareebjamal i see that this issue is still open, if no one has picked it, can i take up this issue and start working on it

**Comment by iamareebjamal** [comment]
yes if you can still reproduce it

**Comment by YugN17** [comment]
i want to work on this
can you assign me

**Comment by YugN17** [comment]
@mariobehling i want to work on this can you assign  me

**Comment by iamareebjamal** [comment]
We don't assign issues. Please send a PR
