### ISSUE TITLE
Search for Organisers (Like EventBrite)

### ISSUE THREAD

**Issue by RotBolt** [fossasia/open-event-attendee-android#1611]
**Describe the feature you'd like**
EventBrite gives option to search for organisers

**Screenshots**
From EventBrite
<img src="https://user-images.githubusercontent.com/24780524/56091016-ef218e00-5ec6-11e9-82bd-34c975490ff3.jpeg" width=360>

**Additional context**
This would require work on server : https://github.com/fossasia/open-event-server/issues/5798

**Would you like to work on the issue?**

- [ :heavy_check_mark:  ] Yes
- [ ] No
- Other:

**Comment by ajax-07** [comment]
if is it still open i want to work on this issue
