### ISSUE TITLE
Refractor favorite sections

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#1652]
**Describe the feature you'd like**
Currently, the favorite event is cached inside the app. We can use the API endpoint: https://api.eventyay.com/v1/user-favourite-events to store it in the server and fetch it whenever the user is logged in

@iamareebjamal Please give some thoughts on this

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Store locally for non logged in person and store on server for logged in person

**Comment by aggarwalpulkit596** [comment]
@anhanh11001 are you working on this ?

**Comment by anhanh11001** [comment]
@aggarwalpulkit596 Yes I'm

**Comment by aggarwalpulkit596** [comment]
@anhanh11001 any update on this if not can I work on this?

**Comment by anhanh11001** [comment]
@aggarwalpulkit596 Yes, please go ahead to take over if you are free now

**Comment by aggarwalpulkit596** [comment]
@anhanh11001 cool

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal should I update the favorite list on the server if the user logs or only update favourite which are marked after the user is logged in

**Comment by iamareebjamal** [comment]
First
