### ISSUE TITLE
Integrate In-App Update API 

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-attendee-android#1823]
References
https://developer.android.com/guide/app-bundle/in-app-updates

**Would you like to work on the issue?**
- [x] Yes

**Comment by liveHarshit** [comment]
Working on it :+1:

**Comment by aggarwalpulkit596** [comment]
@liveHarshit lmk if you need any help as i have already implemented in most of my projects

**Comment by liveHarshit** [comment]
> @liveHarshit lmk if you need any help as i have already implemented in most of my projects

Yes, How to test the implementation? :sweat_smile:

**Comment by aggarwalpulkit596** [comment]
Used flexible or the forced one ?

**Comment by liveHarshit** [comment]
> Used flexible or the forced one ?

```java
val appUpdateManager = AppUpdateManagerFactory.create(this)
        val appUpdateInfoTask = appUpdateManager.appUpdateInfo
        appUpdateInfoTask.addOnSuccessListener { appUpdateInfo ->
            if (appUpdateInfo.updateAvailability() == UpdateAvailability.UPDATE_AVAILABLE) {
                appUpdateManager.startUpdateFlowForResult(
                    appUpdateInfo,
                    AppUpdateType.IMMEDIATE,
                    this,
                    UPDATE_REQUEST_CODE)
            }
        }
```

**Comment by aggarwalpulkit596** [comment]
Immediate is the forced one 😅 and testing is little bit tricky and length process will share code snippet with you although this looks good to me

**Comment by liveHarshit** [comment]
Yes, but hot to debug the implementation?

**Comment by liveHarshit** [comment]
And what about flexible one?

**Comment by aggarwalpulkit596** [comment]
Both of them have to be tested in similar manner you can't debug it you actually have to test using a mock update will share it tonight don't have my laptop right now and difference between flexible and forced it that in case of flexible user might not update the app and can use the app while the update is happening whereas immediate shows user a different screen and can't use the app whole updating the app although can reject and opt not to update

**Comment by liveHarshit** [comment]
> it you actually have to test using a mock update will share it tonight

@aggarwalpulkit596 What is the status?

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal can I start working on this? :P

**Comment by liveHarshit** [comment]
> @iamareebjamal can I start working on this? :P

Please go ahead

**Comment by aggarwalpulkit596** [comment]
@liveHarshit you made a PR why it was closed? Any Specific reason

**Comment by liveHarshit** [comment]
> @liveHarshit you made a PR why it was closed? Any Specific reason

It was not completed.

**Comment by aggarwalpulkit596** [comment]
Cool

**Comment by scixor** [comment]
is this done or can I work on it?
