### ISSUE TITLE
Allow getting tickets without log in

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#1869]
**Describe the feature you'd like**
Allow getting tickets without log in

**Would you like to work on the issue?**
Open to all

**Comment by tronku** [comment]
I am new to the community and I am interested to work on this issue. Just want to know how do you want to take personal info for registration?

**Comment by tronku** [comment]
There's one issue with this feature. To fetch the custom forms, we have to make a network call and for the call to be successful, authorization is needed otherwise we get a HTTP 401 exception.

**Comment by iamareebjamal** [comment]
Open an issue on server to remove authentication check for custom forms
