### ISSUE TITLE
Add contact event organizer

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#1964]
**Describe the feature you'd like**
Add contact event organizer using email of user that create event. 
@iamareebjamal should I use the email attached to organizer (user) of the event to make this feature?
```
"organizers": {
        "links": {
          "self": "/v1/events/1/relationships/organizers",
          "related": "/v1/users"
        }
```

**Would you like to work on the issue?**
Open to all

**Comment by ranjsa** [comment]
@anhanh11001  Can I start working on this .?

**Comment by anhanh11001** [comment]
please go ahead

**Comment by ranjsa** [comment]
@liveHarshit  @anhanh11001  how do we wish to contact event organizer ....through email right ?

**Comment by anhanh11001** [comment]
@ranjsa yes

**Comment by ranjsa** [comment]
@anhanh11001 @liveHarshit  Which email should i use to contact organizer ,
 I think there is only one email linked to Event ( i.e. paypalEmail ) should i use that ?

**Comment by liveHarshit** [comment]
> Or I think it would be good if we include organizersEmail in the database from serverside

No. Check if there is an attribute or relationship for the owner details. If not then it needs to be implemented on the server first. API docs: https://open-event-api-dev.herokuapp.com
