### ISSUE TITLE
Add feature for push notification

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#1968]
**Describe the feature you'd like**
Add push notifications

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
Did we integrate one signal on the server for this?

**Comment by iamareebjamal** [comment]
No

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal There is no support on the server-side but there is an endpoint for Notification should I integrate that?

**Comment by iamareebjamal** [comment]
Already there I guess
