### ISSUE TITLE
Display ticket prices in event details fragment

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#1990]
To match with Eventbrite

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
@iamareebjamal Should I raise an issue on the server to add an attribute for the ticket price range in Events or solve this issue by fetching tickets in event details fragment?

**Comment by iamareebjamal** [comment]
ticket price range?

Add a screenshot of what you want to achieve

**Comment by liveHarshit** [comment]
> ticket price range?
> 
> Add a screenshot of what you want to achieve

<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/59960836-37bf7e00-94ec-11e9-80b9-7a4ac64bfef2.png" height = "480" width="270"> 
<img src="https://user-images.githubusercontent.com/27783786/59960837-38581480-94ec-11e9-946c-29333a8201b3.jpg" height = "480" width="270"> 
</p>

**Comment by iamareebjamal** [comment]
Open server issue
