### ISSUE TITLE
Back button is not working in search location fragment

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2011]
**Would you like to work on the issue?**

yes

**Comment by liveHarshit** [comment]
@anhanh11001 Back press does not work until `Iconified` is set to true and here default Iconified value is false. So back press will never work with that implementation, so search view can be replaced by edit text safely. Are you okay with it?

**Comment by liveHarshit** [comment]
I have tried by commenting on each method, replacing search view with edit text. Also, there are no logs related to that. I don't understand why it is happening. @anhanh11001 Is it reproducible from your side?

**Comment by anhanh11001** [comment]
It's reproducible in my device, not sure why for now, I'll take a closer look later this evening

**Comment by anhanh11001** [comment]
It's because of requesting focus on SearchView, but I still don't know the root cause.

A workaround I tried is to change the SearchView into EditText and it should work find

<img src="https://i.ibb.co/cN1jQM4/1.png" alt="1" border="0">
<img src="https://i.ibb.co/Cpcw2Hv/2.png" alt="2" border="0">

**Comment by liveHarshit** [comment]
@anhanh11001 I have already tried with replacing search view with edit text, it not working. Please read my earlier comment.

**Comment by liveHarshit** [comment]
> it should work fine

Have you tested on device?

**Comment by anhanh11001** [comment]
Yes I did, let me try it again and then send you the GIF

**Comment by anhanh11001** [comment]
What's your device info again?

**Comment by liveHarshit** [comment]
Noughat 7.1.1

**Comment by liveHarshit** [comment]
Let me test on a different device with edit text

**Comment by liveHarshit** [comment]
Not working on Android 10 API Q also, with edit text. Changes : https://github.com/liveHarshit/open-event-android/commit/3028850a9d5c738be77ee453aa34a5fcd8a31512
