### ISSUE TITLE
Skip button appear in AuthFragment wrongly

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#2063]
**Describe the bug**
Skip button should only appear once  in AuthFragment when app created

**Screenshots**
<img src="https://i.ibb.co/xJSrqSc/ezgif-4-7889bc4f895d.gif" alt="ezgif-4-7889bc4f895d" border="0">

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment]
I think it is due to value is not updated with shared preferences, Because when we exit app on the welcome screen, then the screen does not appear again and directly redirect to events without going through login/signup.
