### ISSUE TITLE
Do not open tickets if the order status is not completed

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2077]
**Describe the bug**
Currently, tickets are fetching if the order status is incompleted.

**Would you like to work on the issue?**

Open for all

**Comment by captain82** [comment]
@liveHarshit I would like to work on this issue.

**Comment by liveHarshit** [comment]
> @liveHarshit I would like to work on this issue.

Please go ahead. Also, we assign one issue at a time. For reference #1932

**Comment by captain82** [comment]
@liveHarshit I will work on this issue first.

**Comment by captain82** [comment]
@liveHarshit Can you describe a little what exactly needs to happen?

**Comment by liveHarshit** [comment]
> @liveHarshit Can you describe a little what exactly needs to happen?

In the tickets section, order status is displaying for tickets. Sometimes an order is pending(due to incomplete payment), then instead of opening ticket details, it should redirect for payment. And for another status (canceled or expire), only a message should display.
Open the ticket only when order is completed or placed(in case of offline payment)

**Comment by captain82** [comment]
@liveHarshit ok Thank you

**Comment by captain82** [comment]
@liveHarshit How do I make an incomplete payment order?

**Comment by liveHarshit** [comment]
> @liveHarshit How do I make an incomplete payment order?

With order identifier. Check how order is creating in attendee fragment. API docs: https://open-event-api-dev.herokuapp.com

**Comment by captain82** [comment]
@liveHarshit when the status is pending the user should be redirected to Attendee Fragment where the countdown of 15 minutes begins to complete the payment,right?

**Comment by liveHarshit** [comment]
> @liveHarshit when the status is pending the user should be redirected to Attendee Fragment where the countdown of 15 minutes begins to complete the payment,right?

I'm not sure if we can update attendees. Please check the frontend implementation. 
Debug: https://open-event-fe.netlify.com
Release: eventyay.com

**Comment by captain82** [comment]
Thanks @liveHarshit

**Comment by captain82** [comment]
@liveHarshit When i try pay using paymal sandbox ,it says your selected payment method was not accepted although.Any help?

**Comment by liveHarshit** [comment]
> @liveHarshit When i try pay using paymal sandbox ,it says your selected payment method was not accepted.Need help.

Use client Id: `AXrRge-gN1E5WHMYsu0FsftPOWBjTu3Sqj0pKfpq7mPKwv6w_ikiqWrka_06lAWZW5_WxL9CwaMiTVsc` with the debug server.

**Comment by captain82** [comment]
@liveHarshit Pending Tickets are now being paid successfully using paypal .How do i test for Stripe payment.I am unable to create a event with stripe as payment method.

**Comment by liveHarshit** [comment]
> @liveHarshit Pending Tickets are now being paid successfully using paypal .How do i test for Stripe payment.I am unable to create a event with stripe as payment method.

If it is working with PayPal then do the same for stripe.

**Comment by captain82** [comment]
@liveHarshit how do i test it?
I mean how can i make a pending Event with stripe as payment method.As of now only paypal is showing

**Comment by captain82** [comment]
@liveHarshit I think pending orders cannot be created only with PayPal. Everything else is completed.

**Comment by liveHarshit** [comment]
> @liveHarshit I think pending orders can be created only with PayPal and not Stripe as no parameter is obtained for card details. If a user chooses Stripe payment it can either be a success or failure during first-time ticket booking. Correct me if I am wrong?

User needs to enter details again.

**Comment by captain82** [comment]
@liveHarshit So do i have to make a new screen for that?

**Comment by liveHarshit** [comment]
> user should be redirected to Attendee Fragment

**Comment by captain82** [comment]
@liveHarshit Are you sure?
Because the same could have been done for Paypal

**Comment by liveHarshit** [comment]
> @liveHarshit Are you sure?
> Because the same could have been done for Paypal

What if the user wants to pay with stripe. Open attendee section with same order identifier. So that order will complete after payment is done. Got it?

**Comment by liveHarshit** [comment]
@iamareebjamal Your opinion?

**Comment by captain82** [comment]
> > @liveHarshit Are you sure?
> > Because the same could have been done for Paypal
> 
> What if the user wants to pay with stripe. Open attendee section with same order identifier. So that order will complete after payment is done. Got it?

I think this is possible .Lets see what @iamareebjamal says

**Comment by captain82** [comment]
@liveHarshit Should i proceed with your mentioned method or wait for @iamareebjamal

**Comment by iamareebjamal** [comment]
Yes

**Comment by captain82** [comment]
@liveHarshit I want to make a PR for this bug

**Comment by liveHarshit** [comment]
> @liveHarshit I want to make a PR for this bug

Yes please.

**Comment by captain82** [comment]
@liveHarshit ok

**Comment by captain82** [comment]
@liveHarshit Just made a PR.

**Comment by kshitij-99** [comment]
Please close this issue.

**Comment by liveHarshit** [comment]
> Please close this issue.

Why?

**Comment by tusharr-98** [comment]
Is this issue still open ??...would like to work on it.

**Comment by rob729** [comment]
@liveHarshit Can I work on this issue?

**Comment by liveHarshit** [comment]
There is already a PR. @captain82 What is the status?

**Comment by iamareebjamal** [comment]
2 months, so most likely won't continue

**Comment by liveHarshit** [comment]
@rob729 Go ahead. First read all comments on the previous PR and understand the issue.

**Comment by tusharr-98** [comment]
@liveHarshit I have asked first if I can work on this issue or not. Please assign it to me.

**Comment by rob729** [comment]
@tusharr-98 Are you still working on this issue?

**Comment by tusharr-98** [comment]
@rob729  yes...I have asked some questions related to the last PR from @liveHarshit but haven't got any reply.

**Comment by iamareebjamal** [comment]
Where's the question?

**Comment by tusharr-98** [comment]
https://github.com/fossasia/open-event-attendee-android/pull/2356#discussion_r349884297

**Comment by tusharr-98** [comment]
@liveHarshit, how should I get the order and event by their ids as they are required as a parameter to start PayPal payment?

**Comment by liveHarshit** [comment]
> @liveHarshit, how should I get the order and event by their ids as they are required as a parameter to start PayPal payment?

From order fragment and order under user view model.

**Comment by tusharr-98** [comment]
@liveHarshit can I write the code for payment in the order under user view model ?

**Comment by tusharr-98** [comment]
Also...I am unable to create a pending order, need help

**Comment by tusharr-98** [comment]
Also every time I am trying to create order...snackbar appears with a message "unable to create order".

**Comment by rob729** [comment]
@tusharr-98 Are you still working on this issue?

**Comment by tusharr-98** [comment]
@rob729  are you able to create Order ??

**Comment by thatfedupguy** [comment]
@liveHarshit help needed

**Comment by liveHarshit** [comment]
> @liveHarshit help needed

yes?

**Comment by thatfedupguy** [comment]
@liveHarshit I am unable to create pending order

**Comment by iamareebjamal** [comment]
You are a developer, not a user. We need more information like the logs and server endpoint, request and response of the failing call

**Comment by thatfedupguy** [comment]
I mean what i have to do to create a pending order. I have gone through the code but cannot figure it out.

**Comment by iamareebjamal** [comment]
Use API or frontend

**Comment by aryanguls** [comment]
I'll work on this and do it.

**Comment by rob729** [comment]
@nikit19 @liveHarshit @iamareebjamal I am not able to create a pending order. Can you please help me in creating one?

**Comment by liveHarshit** [comment]
> @nikit19 @liveHarshit @iamareebjamal I am not able to create a pending order. Can you please help me in creating one?

Create order, do not make payment.

**Comment by rob729** [comment]
<img src = "https://user-images.githubusercontent.com/31350501/73536240-87373680-444b-11ea-846e-baecfda09dec.png" height = 400>

I am getting "error in fetching tickets" error.

Logs:-
E/EventDetailsViewModel$syncTickets: Error fetching tickets
    com.github.jasminb.jsonapi.exceptions.InvalidJsonApiResourceException: Included must be an array of valid resource objects, or an empty array ([])

What could be the possible reason for this error?

**Comment by rob729** [comment]
@dheerajkotwani Are you facing this issue?

> <img alt="" height="400" src="https://user-images.githubusercontent.com/31350501/73536240-87373680-444b-11ea-846e-baecfda09dec.png">
> 
> I am getting "error in fetching tickets" error.
> 
> Logs:-
> E/EventDetailsViewModel$syncTickets: Error fetching tickets
> com.github.jasminb.jsonapi.exceptions.InvalidJsonApiResourceException: Included must be an array of valid resource objects, or an empty array ([])
> 
> What could be the possible reason for this error?

**Comment by dheerajkotwani** [comment]
while opening ticket it is giving error
Logs:
`
2020-01-31 20:07:06.036 12422-12422/com.eventyay.attendee E/TicketsViewModel$loadTickets: Error fetching tickets 9
    com.github.jasminb.jsonapi.exceptions.InvalidJsonApiResourceException: Included must be an array of valid resource objects, or an empty array ([])
        at com.github.jasminb.jsonapi.ValidationUtils.ensureValidResourceObjectArray(ValidationUtils.java:82)
        at com.github.jasminb.jsonapi.ResourceConverter.getIncludedResources(ResourceConverter.java:423)
        at com.github.jasminb.jsonapi.ResourceConverter.parseIncluded(ResourceConverter.java:388)
        at com.github.jasminb.jsonapi.ResourceConverter.readDocumentCollection(ResourceConverter.java:281)
        at com.github.jasminb.jsonapi.retrofit.JSONAPIResponseBodyConverter.convert(JSONAPIResponseBodyConverter.java:35)
        at com.github.jasminb.jsonapi.retrofit.JSONAPIResponseBodyConverter.convert(JSONAPIResponseBodyConverter.java:15)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)
        at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)
        at io.reactivex.Flowable.subscribe(Flowable.java:14882)
        at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.onNext(FlowableSwitchMap.java:129)
        at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.innerSuccess(FlowableFlatMapMaybe.java:175)
        at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber$InnerObserver.onSuccess(FlowableFlatMapMaybe.java:397)
        at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:61)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:132)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)`

**Comment by iamareebjamal** [comment]
Can't help unless you give request URL and response

**Comment by dheerajkotwani** [comment]
https://open-event-api-dev.herokuapp.com/v1/events/126/tickets?include=event&fields

{"data": [{"type": "ticket", "attributes": {"is-fee-absorbed": true, "min-price": 1.0, "min-order": 1, "price": 0.0, "is-checkin-restricted": true, "max-order": 10, "deleted-at": null, "position": 1, "max-price": 0.0, "type": "free", "sales-starts-at": "2020-01-14T13:03:49.335000+00:00", "is-description-visible": true, "name": "free2", "sales-ends-at": "2020-02-12T18:30:00+00:00", "auto-checkin-enabled": false, "description": null, "quantity": 50, "is-hidden": false}, "relationships": {"access-codes": {"links": {"self": "/v1/tickets/131/relationships/access-codes", "related": "/v1/tickets/131/access-codes"}}, "event": {"links": {"self": "/v1/tickets/131/relationships/event", "related": "/v1/tickets/131/event"}, "data": {"type": "event", "id": "126"}}, "attendees": {"links": {"self": "/v1/tickets/131/relationships/attendees", "related": "/v1/attendees?ticket_id=131"}}, "ticket-tags": {"links": {"self": "/v1/tickets/131/relationships/ticket-tags", "related": "/v1/tickets/131/ticket-tags"}}, "discount-codes": {"links": {"self": "/v1/tickets/131/relationships/discount-codes", "related": "/v1/tickets/131/discount-codes"}}}, "id": "131", "links": {"self": "/v1/tickets/131"}}, {"type": "ticket", "attributes": {"is-fee-absorbed": true, "min-price": 1.0, "min-order": 1, "price": 0.0, "is-checkin-restricted": true, "max-order": 10, "deleted-at": null, "position": 0, "max-price": 0.0, "type": "free", "sales-starts-at": "2020-01-13T16:30:14.088000+00:00", "is-description-visible": true, "name": "free", "sales-ends-at": "2020-02-12T18:30:00+00:00", "auto-checkin-enabled": false, "description": null, "quantity": 10, "is-hidden": false}, "relationships": {"access-codes": {"links": {"self": "/v1/tickets/128/relationships/access-codes", "related": "/v1/tickets/128/access-codes"}}, "event": {"links": {"self": "/v1/tickets/128/relationships/event", "related": "/v1/tickets/128/event"}, "data": {"type": "event", "id": "126"}}, "attendees": {"links": {"self": "/v1/tickets/128/relationships/attendees", "related": "/v1/attendees?ticket_id=128"}}, "ticket-tags": {"links": {"self": "/v1/tickets/128/relationships/ticket-tags", "related": "/v1/tickets/128/ticket-tags"}}, "discount-codes": {"links": {"self": "/v1/tickets/128/relationships/discount-codes", "related": "/v1/tickets/128/discount-codes"}}}, "id": "128", "links": {"self": "/v1/tickets/128"}}], "included": [{"type": "event", "id": "126", "links": {"self": "/v1/events/126"}}], "links": {"self": "/v1/events/126/tickets?include=event&fields%5Bevent%5D=id&page%5Bsize%5D=0"}, "meta": {"count": 2}, "jsonapi": {"version": "1.0"}}

**Comment by iamareebjamal** [comment]
The URL is invalid

**Comment by dheerajkotwani** [comment]
https://open-event-api-dev.herokuapp.com/v1/events/126/tickets?include=event&fields[event]=id&page[size]=0

**Comment by iamareebjamal** [comment]
Revert jsonapi-converter to previous version and see if it is working

**Comment by iamareebjamal** [comment]
Add this DeserializationFeature to true - ALLOW_UNKNOWN_TYPE_IN_RELATIONSHIP

**Comment by dheerajkotwani** [comment]
Reverting the dependency worked

**Comment by iamareebjamal** [comment]
It's better if you use ALLOW_UNKNOWN_TYPE_IN_RELATIONSHIP

**Comment by dheerajkotwani** [comment]
unable to resolve, how to use this

**Comment by rob729** [comment]
> It's better if you use ALLOW_UNKNOWN_TYPE_IN_RELATIONSHIP

@iamareebjamal  Can you please tell me in which file this change has to be made?

**Comment by iamareebjamal** [comment]
Read the docs of the library
