### ISSUE TITLE
Unable to click back press in SearchLocationFragment

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#2085]
**Describe the bug**
Unable to click back press in SearchLocationFragment

**Would you like to work on the issue?**
Yes

**Comment by anhanh11001** [comment]
@liveHarshit Can you check if it is reproducible in your device, it is in my and it's weird cause I thought you sent a PR earlier

**Comment by liveHarshit** [comment]
Yes, It was solved at that time. Will check again :+1:
