### ISSUE TITLE
User shouldn't be able to get more tickets/per order than organizer settings

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#2091]
**Describe the bug**
User shouldn't be able to get more tickets/per order than organizer settings. 
Also, UI doesn't look good
Example: User can get a maximum of 10 tickets, but we can still get like 9 free tickets, 9 paid tickets A, 9 paid tickets B -> 27 tickets/order

**Screenshots**
<img src="https://i.ibb.co/x8jTdWT/66488535-428151587779432-6888523283835125760-n.jpg" width="300">

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment]
I'm confused about this issue. When I created an event and buy tickets, tickets are displaying according to the max and min numbers which I have entered during creation.

**Comment by anhanh11001** [comment]
Let me edit it, so you can get maximum of 10 tickets, but we can still get like 9 free tickets, 9 paid tickets A, 9 paid tickets B -> 27 tickets/order

**Comment by anhanh11001** [comment]
Checked frontend, it is not a bug. So I'm closing this issue
