### ISSUE TITLE
Edit Profile section does not close after updating image

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-attendee-android#2107]
**Describe the bug**
Currently, after updating the image and leaving the first name and last name blank, Edit Profile section doesn't close. If back button is pressed, a dialog box pops up asking for saving the details even if the details have already been saved. On clicking 'Save' in the dialog box, it closes,  and user remains on the Edit Profile section again. Only way to leave the section is to press the 'Discard' button in the dialog.

**Steps to reproduce**
1. Ensure that first name and last name are empty.
2. Select a profile picture.
3. Save the details.

**Expected behavior**
Edit Profile section should close after image is saved.

**Would you like to work on the issue?**
Open to all.

**Comment by anhanh11001** [comment]
I'm taking it up now
