### ISSUE TITLE
Add these changes to fdroid metadata

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-attendee-android#2122]
Latest changes are not compatible with fdroid build server, please add these to the fdroid metadata

https://gitlab.com/fdroid/fdroiddata/merge_requests/5053/diffs

What it should look like after the changes
https://gitlab.com/fdroid/fdroiddata/merge_requests/5055/diffs

**Comment by liveHarshit** [comment]
How to follow the procedure, should I create MR on GitLab?

**Comment by iamareebjamal** [comment]
Yes

**Comment by liveHarshit** [comment]
Please check MR: https://gitlab.com/fdroid/fdroiddata/merge_requests/5083

**Comment by adityastic** [comment]
@liveHarshit fix pipeline

**Comment by liveHarshit** [comment]
Merged
