### ISSUE TITLE
Stripe not working

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2133]
Charge class is not matching with the server documentation.

For PayPal same endpoint can be used - 
![image](https://user-images.githubusercontent.com/27783786/61267378-5ba57500-a7b5-11e9-8920-a5d0aab9fae5.png)

**Would you like to work on the issue?**

yes

**Comment by liveHarshit** [comment]
Stripe will not work like that. Here we are just creating a token from the server using card data, not completing the payment.
https://stackoverflow.com/a/50233021

**Comment by liveHarshit** [comment]
For now, if we redirect to the frontend, stripe, and PayPal both will work with the same implementation. Later Braintree implementation can handle both.

**Comment by iamareebjamal** [comment]
No, we need stripe to be implemented separately as an organizer may want to enable stripe on server and not braintree

**Comment by anhanh11001** [comment]
>Stripe will not work like that. Here we are just creating a token from the server using card data, not completing the payment.

We do create the token in the client-side and then send the success token to the server.
<img src="https://i.ibb.co/ww8vrKy/stripe.png" alt="stripe" border="0">

Can you tell me which part of the code is not correct?

**Comment by liveHarshit** [comment]
> Stripe will not work like that. Here we are just creating a token from the server using card data, not completing the payment.
> https://stackoverflow.com/a/50233021

@anhanh11001

**Comment by liveHarshit** [comment]
It's only creating a token from the card data, not completing the payment.

**Comment by anhanh11001** [comment]
Ok so here is what we want right:
Collect card data (client) -> Create a stripe token using Stripe SDK (client) -> send token to the server (client) -> make payment (server) -> Finallize payment
Is it correct?

Because it is what is implemented. When we send the Charge object to the server, the server will handle the payment, send us the response and then we finalize it. We don't use Stripe SDK to make the charge, but our own API to make the charge

**Comment by liveHarshit** [comment]
> > make payment (server) ->

Yes but here, how the server is handling the payment, Where the user is verifying the card with OTP or protected password!

**Comment by liveHarshit** [comment]
With the test key, the server is throwing an error and the same in the production app also.

**Comment by iamareebjamal** [comment]
OK, open an issue about test key not working as expected and mention what you sent and what you expect in response

**Comment by liveHarshit** [comment]
@iamareebjamal I think test API key will not work with production server as `"detail": "Request req_SJK4iedFbc3COs: No such token: tok_1EwoTzDaIjXFQnUghsf4zKpy"`  and there is no option for the stripe in debug server.

**Comment by iamareebjamal** [comment]
Open an issue about enabling stripe in dev instance

**Comment by liveHarshit** [comment]
@iamareebjamal I want to confirm if it is a server-side problem. As it is not working on frontend https://github.com/fossasia/open-event-frontend/issues/3310 and no one responding on Gitter also.

**Comment by liveHarshit** [comment]
Stripe is fixed on the server and working. Now we need to handle different HTTP errors, but it requires the API key. Test key is not working with the server.
@mariobehling @iamareebjamal One thing can be done if FOSSASIA create a test event with the API key then we can test it and get the refund later. As stripe account cannot be activated in India.

**Comment by iamareebjamal** [comment]
Use debug server
