### ISSUE TITLE
Make billing info compulsory for paid orders

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2134]

**Comment by iamareebjamal** [comment]
Confirm if server is throwing error if it is not included

**Comment by liveHarshit** [comment]
> Confirm if server is throwing error if it is not included

Server is not throwing error as the order is creating successfully

**Comment by iamareebjamal** [comment]
Open issue on server. And did you check on production server or development server?

**Comment by liveHarshit** [comment]
> Open issue on server. And did you check on production server or development server?

Both. Issue is already there: https://github.com/fossasia/open-event-server/issues/6137
