### ISSUE TITLE
Enable server configuration field in F-Droid build

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-attendee-android#2142]
Seems like F-Droid maintainers are biased towards which apps get NonFreeNet anti-feature and which don't. So please enable the API URL configuring field in F-Droid build since I don't want to see NonFreeNet anti-feature on FOSSASIA apps which are not only fully built on Open Source technologies, but also give the easiest way to change server instances

Ridiculous policy

**Comment by liveHarshit** [comment]
> enable the API URL configuring field in F-Droid build

Mean add api url under product flavour in gardle?

**Comment by ShridharGoel** [comment]
@liveHarshit Add option for user to change the base URL in F-Droid build
