### ISSUE TITLE
Make name and email mandatory for attendee form

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2148]
**Would you like to work on the issue?**

yes

**Comment by anhanh11001** [comment]
Isn't it the server-side problem in the Custom Form?

**Comment by liveHarshit** [comment]
> Isn't it the server-side problem in the Custom Form?

Yes, I think. Will close if fixed by https://github.com/fossasia/open-event-server/issues/6170#issuecomment-513174515
