### ISSUE TITLE
Change endpoint for discount and access code 

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-attendee-android#2163]
The android issue for https://github.com/fossasia/open-event-server/issues/6027

**Describe the bug**
Change endpoint for retrieving discount code using event_id as in https://github.com/fossasia/open-event-server/pull/6208.

**Expected behavior**
Access code and discount code should work properly.

**Would you like to work on the issue?**

- [ ] Yes
- [x] No

**Comment by anhanh11001** [comment]
are you working on this or should someone from the Android team take this up?

**Comment by prateekj117** [comment]
@anhanh11001 Ya someone else can take this up from Android Team.
