### ISSUE TITLE
Not able to remove favorite events

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2183]
**Logs**
```
D/OkHttp: {"errors": [{"status": 404, "source": {"pointer": ""}, "title": "Object not found", "detail": "Object Not Found"}], "jsonapi": {"version": "1.0"}}
    <-- END HTTP (146-byte body)
D/EventsViewModel$removeFavorite: Fail on removing like for event ID 5
    retrofit2.adapter.rxjava2.HttpException: HTTP 404 NOT FOUND
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
```

**Screenshots**
<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/61929718-60c6a900-af99-11e9-90fd-620193d2ff22.png" height = "480" width="270"> 
</p>

**Smartphone Info:**

API 24

**Additional context**

**Would you like to work on the issue?**

yes

**Comment by liveHarshit** [comment]
@anhanh11001 Can you please look into it. Wrong event id is being sent while removing favorite. Id's are different for removing and adding, so the server is giving `404`

**Comment by anhanh11001** [comment]
OK, I'll look into that tonight

**Comment by anhanh11001** [comment]
It's a server issue, the server doesn't distinguish different user I think

**Comment by anhanh11001** [comment]
@iamareebjamal I have a question, if the model is soft delete, then when I try to send HTTP request to delete a record, the server should still be able to query that record, is it correct?

```
user_favourite_event = UserFavouriteEvent.query.filter_by(
                                   user=current_user, event_id=int(data['event'])).first()
        if user_favourite_event:
            raise ConflictException({'pointer': '/data/relationships/event'}, "Event already favourited")
```
```
class UserFavouriteEvent(SoftDeletionModel):
    __tablename__ = 'user_favourite_events'
```

**Comment by ranjsa** [comment]
@liveHarshit @anhanh11001  Can I please  work on this Issuue if it is unassigned .

**Comment by anhanh11001** [comment]
@ranisa please go ahead

**Comment by ranjsa** [comment]
@liveHarshit  @anhanh11001 
[https://drive.google.com/file/d/1GzLFvi-MVXvCduyIO8MB4J5bU0n78nJ5/view?usp=sharing](url)
can you please tell me is this a server side issue or wrong event id passed through the app 
_event id 20_ is passed through the parameter , but error message is showing "Fail on removing like for event ID 8"

**Comment by ranjsa** [comment]
@liveHarshit @anhanh11001

https://drive.google.com/file/d/1GzLFvi-MVXvCduyIO8MB4J5bU0n78nJ5/view?usp=sharing

can you please tell me is this a server side issue or wrong event id passed through the app
event id 20 is passed through the parameter , but error message is showing "Fail on removing like for event ID 8"

**Comment by anhanh11001** [comment]
@ranjsa 
There are two IDs in this case then, the ID for the Event and the ID for the Favorite Event. Take a look at the implementation in the data class to see the differences between Event and Favorite Event object. From the logs, it seems like one ID has been used for logging and the other ID has been used for sending DELETE request. 

Please take a look at this documentation to see which ID is used to remove favorite event: https://api.eventyay.com/#favourite-events

If you have further questions about the documentation, send a message in the open-event-server Gitter channel to ask for more details

**Comment by aggarwalpulkit596** [comment]
@ranjsa you still working on it ?

**Comment by ranjsa** [comment]
@aggarwalpulkit596 
> @ranjsa you still working on it ?
Yes .. sorry I am working on it .

**Comment by ranjsa** [comment]
@liveHarshit @anhanh11001  Please review https://github.com/fossasia/open-event-attendee-android/pull/2346#partial-pull-merging
