### ISSUE TITLE
 Add prices in for all tickets in TicketIdAndQtyWrapper

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2216]
Currently, the donation ticket price is added others are 0.0

**Would you like to work on the issue?**

yes

**Comment by tusharr-98** [comment]
@liveHarshit can you fill me in more about this issue... I would like to contribute to it.

**Comment by liveHarshit** [comment]
> @liveHarshit can you fill me in more about this issue... I would like to contribute to it.

You can find it in price calculating function in the Attendee fragment view model and ticket view model.

**Comment by rob729** [comment]
@liveHarshit I want to work on this issue.
Can you please tell me how should I proceed on this issue?

**Comment by liveHarshit** [comment]
> > @liveHarshit can you fill me in more about this issue... I would like to contribute to it.
> 
> You can find it in price calculating function in the Attendee fragment view model and ticket view model.

@rob729 Just simplify the variables used. Removed unused ones.

**Comment by rob729** [comment]
Ok.
I am working on this issue.

**Comment by rob729** [comment]
@liveHarshit I think function getAmount() does not have any unused/unnecessary variables.
Can you help in solving this issue?

**Comment by liveHarshit** [comment]
> @liveHarshit I think function getAmount() does not have any unused/unnecessary variables.
> Can you help in solving this issue?

Read comments on PR https://github.com/fossasia/open-event-attendee-android/pull/2206#discussion_r308887610 to understand the issue.
