### ISSUE TITLE
App freeze on click back from AuthFragment to TicketsFragment

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#2240]
**Describe the bug**
App freeze on click back from AuthFragment to TicketsFragment

**Screenshots**
<img src="https://i.ibb.co/L9c9QRn/ezgif-1-005882e9b0f8.gif" alt="ezgif-1-005882e9b0f8" border="0">

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment]
I think is is duplicate of #2235

**Comment by anhanh11001** [comment]
@liveHarshit I think then you can work on both issues, I also guess they are pretty much the same

**Comment by liveHarshit** [comment]
@anhanh11001 Is it reproducible to you now?

**Comment by anhanh11001** [comment]
let me check it again now

**Comment by anhanh11001** [comment]
Huh, it is not reproducible. Closing
