### ISSUE TITLE
App crashes on clicking "View" when having Donation Tickets

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#2241]
**Describe the bug**
App crashes on clicking "View" when having Donation Tickets

**Screenshots**
<img src="https://i.ibb.co/vzjVwQT/ezgif-1-e07e1b780106.gif" alt="ezgif-1-e07e1b780106" border="0">

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment]
Duplicate of #2234

**Comment by liveHarshit** [comment]
@anhanh11001 Sorry I have not mentioned how to reproduce in #2234
