### ISSUE TITLE
Tax included for free orders

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#2242]
**Describe the bug**
Tax included for free orders

**Screenshots**
<img src="https://i.ibb.co/XSs5tGP/ezgif-1-b8dd94043012.gif" alt="ezgif-1-b8dd94043012" border="0">

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment]
Fixed in PR #2237 and duplicate of #2233
