### ISSUE TITLE
Donation tickets made with no donation

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#2243]
**Describe the bug**
Donation tickets made with no donation

**Screenshots**
<img src="https://i.ibb.co/2MsTpK0/ezgif-1-e83337dcfda3.gif" alt="ezgif-1-e83337dcfda3" border="0">

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment]
Please also check the range for minimum and maximum donation.
