### ISSUE TITLE
Map in EventDetailsFragment showing nothing

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#2256]
**Describe the bug**
In event details fragment, sometimes map show nothing

**Screenshots**
<img src="https://i.ibb.co/sbQmHYP/67566482-2207007072761486-3548067273430269952-n.jpg" alt="67566482-2207007072761486-3548067273430269952-n" border="0">

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment]
Debug or production?

**Comment by anhanh11001** [comment]
production, haven't tested in debug

**Comment by liveHarshit** [comment]
I think it is because the organizer has not provided a proper location. you can check other events. It's working.
