### ISSUE TITLE
Remove improvement form from settings and readme

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2280]
**Would you like to work on the issue?**

yes

**Comment by rajput2122** [comment]
Yes, sir, I want to work on this issue. You are saying to remove google doc form that opens after clicking on suggest improvement link, am I right?

**Comment by liveHarshit** [comment]
@rajput2122 Yes, go ahead.

**Comment by rajput2122** [comment]
what do I have to replace it with or simply make it invisible from the setting.xml.Actually, I comment out  the link

**Comment by liveHarshit** [comment]
> what do I have to replace it with or simply make it invisible from the setting.xml.Actually, I comment out the link

removing is not replacing or commenting out.

**Comment by rajput2122** [comment]
Actually, sir, I asked you for confirmation as I am beginning open source contribution 
thanks sir, I am going to remove this option from setting

**Comment by rajput2122** [comment]
I have done this sir. Sorry for late. How to make a pull request sir?

**Comment by liveHarshit** [comment]
> I have done this sir. Sorry for late. How to make a pull request sir?

Instead Google it, learn Git and GitHub well. 
And we assign one issue at a time so first, send PR for one issue then ask to work on another issue.
