### ISSUE TITLE
Add uploading audio/slides/video in Speakers Call Fragment

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#2291]
**Describe the feature you'd like**
Add uploading audio/slides/video in Speakers Call Fragment

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Not a priority

**Comment by Zyro9922** [comment]
I want to work on this. Please provide more details.

**Comment by anhanh11001** [comment]
@Zyro9922 please go ahead. In Eventyay, Speakers Call proposal can contain audio/slides/video from the speaker. The feature is to:
1. Import audio/slides/video from Android device to the app
2. Upload that file into the server and receive the file URL
3. Update Proposal by PATCH request with the URL attached to it.

The process should be similar like uploading an image to the server and then update a user profile with that image.

Details of HTTP requests can be found in https://api.eventyay.com/

**Comment by Zyro9922** [comment]
Thank You. I'll start the work.

**Comment by Zyro9922** [comment]
**Update**

I have created a local server and a prototype android app to upload images to make sure everything works fine.
I'll have to delay this issue for a week as I have exams.

**Comment by iamareebjamal** [comment]
You could use https://open-event-api-dev.herokuapp.com
