### ISSUE TITLE
Check unverified user by error 

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2306]
**Describe the chore**
Check unverified user by error instead of details as server PR is merged

**Would you like to work on the issue?**

yes

**Comment by liveHarshit** [comment]
@iamareebjamal Is it correct, there should be title instead of code?
![image](https://user-images.githubusercontent.com/27783786/63571622-55699c00-c59e-11e9-92ee-1802760bfdc9.png)

**Comment by iamareebjamal** [comment]
No

**Comment by liveHarshit** [comment]
> No

No for which part?

**Comment by iamareebjamal** [comment]
You should check code and take appropriate action
