### ISSUE TITLE
Fix stripe error

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2341]
**Describe the bug**
Bump stripe and fix errors.
PR: https://github.com/fossasia/open-event-attendee-android/pull/2342

**Comment by iamareebjamal** [comment]
Please don't use non standard labels. Github extracts exactly `good-first-issue` to show to new contributors. If you change it to `Good first issue` or `good fIrSt issue`, only people viewing the repository will see it

**Comment by rob729** [comment]
@liveHarshit Can I work on this issue?

**Comment by liveHarshit** [comment]
> @liveHarshit Can I work on this issue?

Go ahead.

**Comment by rob729** [comment]
@liveHarshit Should I send the PR now or tomorrow for the PR to be considered in Codeheat?

**Comment by liveHarshit** [comment]
> @liveHarshit Should I send the PR now or tomorrow for the PR to be considered in Codeheat?

Send anytime, it will be considered.

**Comment by rahulmalhotra236** [comment]
I wanna work on this issue. Please assign this to me.
