### ISSUE TITLE
Make write a feedback optional . 

### ISSUE THREAD

**Issue by ranjsa** [fossasia/open-event-attendee-android#2355]
**During submitting a feedback about a event Write a feedback should be optional , like in most of the apps.**

**Screenshots**
![screen2](https://user-images.githubusercontent.com/43692789/65320279-22c3bb00-dbbf-11e9-80f7-1000c82da139.png)

**Additional context**

Google play store also has the same feature 

![screen3](https://user-images.githubusercontent.com/43692789/65320800-4fc49d80-dbc0-11e9-9121-091f4085e530.png)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
This is not an Android issue. This is a server issue. Open an issue there and when it is accepted. I'll reopen this
