### ISSUE TITLE
Notification dot's abrupt behaviour

### ISSUE THREAD

**Issue by tronku** [fossasia/open-event-attendee-android#2357]
**Describe the bug**
Notification red dot appears even when there is no new notification.

**To Reproduce**
1. Go to Events tab. You can observe the red dot now.
2. Open the notification section by clicking on the bell.
3. Go back to Events tab. Now the red dot is removed.
4. Go to another tab, let's say Search and go back to Events tab to refresh the content.
5. You can observe the red dot again. Now, there will be no new notifications even then dot is visible.

**Expected behavior**
Notification dot should not appear when there is no new notification.

**Smartphone Info:**
Device - Mi Note 5
Android Version - Oreo (8.1)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by adityastic** [comment]
@tusharr-98 try to reproduce

**Comment by tusharr-98** [comment]
https://giphy.com/gifs/KbYHKdu20mhAqt0Uke/html5

**Comment by tusharr-98** [comment]
[https://giphy.com/gifs/KbYHKdu20mhAqt0Uke/html5](url)

**Comment by tusharr-98** [comment]
Yeah the red dot appears every time the  event fragment is refreshed even if there is no notification

**Comment by tusharr-98** [comment]
[https://media.giphy.com/media/KbYHKdu20mhAqt0Uke/giphy.gif](url)

**Comment by adityastic** [comment]
@tusharr-98 go ahead then

**Comment by tronku** [comment]
@adityastic I have already asked for working on it in the description while creating the issue but didn't get any reply. I have been working on it.

**Comment by adityastic** [comment]
@tusharr-98 I'm sorry,@tronku is still working on it. Lets wait for his pr

**Comment by tronku** [comment]
@adityastic please review the pull request #2379
