### ISSUE TITLE
Build error for release: Google Api Error

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2373]
**Describe the bug**
```
[!] Google Api Error: validateAppMessageTooManyScreenshots: This app has more than 8 screenshots for language en-US. - This app has more than 8 screenshots for language en-US.
```

https://travis-ci.org/fossasia/open-event-attendee-android

**Comment by adityastic** [comment]
Yes, the maximum allowed screenshot number for a category is 8.

**Comment by liveHarshit** [comment]
> Yes, the maximum allowed screenshot number for a category is 8.

Sending PR to master branch

**Comment by aggarwalpulkit596** [comment]
@liveHarshit close this
