### ISSUE TITLE
Similar events layout collapses at end

### ISSUE THREAD

**Issue by tronku** [fossasia/open-event-attendee-android#2390]
**Describe the bug**
In the EventDetailFragment, the similar events layout collapses at the end of the pagination. 

**To Reproduce**
1. Go to the Events tab.
2. Click on any event in the recyclerview.
3. Scroll down to the end for the "More like this" section.
4. Swipe right till the end of the pagination.

**Expected behavior**
The layout should be gone only when there are no similar events on the list. In the rest of the cases, it should be there in the UI.

**Screenshots**
![ezgif-1-e627d8f5a55c](https://user-images.githubusercontent.com/31654207/66715700-fa0c9b00-ede3-11e9-91fe-3b526c18378d.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Redmi Note 5 |
|Android Version|  Oreo 8.1 |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by tronku** [comment]
I would like to work on the issue.

**Comment by liveHarshit** [comment]
go ahead
