### ISSUE TITLE
UI conflict in Ticket Section in The App ! it's crossing the layout awwfully doesn't look good

### ISSUE THREAD

**Issue by Rajchowdhury420** [fossasia/open-event-attendee-android#2413]
**Describe the bug**
I think its awwfully overriding the the ideal Layout

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**
[image](http://www.mediafire.com/view/i0ay5cf4zl40ctb/WhatsApp%20Image%202019-11-06%20at%2020.47.48.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung J7 Max|
|Android Version| Oreo 8.1    |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by rob729** [comment]
@liveHarshit Can I work on this issue?

**Comment by liveHarshit** [comment]
> @liveHarshit Can I work on this issue?

Go ahead.
