### ISSUE TITLE
When clicked on Profile in Settings page it ask user for logout

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-attendee-android#2419]
**Describe the bug**
Clicking on Profile option in Settings Activity opens a dialog asking user to logout

**To Reproduce**
1. Go to Settings Page
2. Click on Profile
3. See error

**Expected behavior**
When clicked on Profile Option in Settings Activity then Profile Page should open or there should be a button for logout

**Screenshots**
![s1](https://user-images.githubusercontent.com/44086235/68541139-e3953780-03c1-11ea-840c-5cb6f2f94833.gif)
![s2](https://user-images.githubusercontent.com/44086235/68541140-e3953780-03c1-11ea-8982-ddf76aa7ac9a.gif)

**Smartphone Info:**
<table>
<tr>
  <td>Device</td><td>Redmi Note 4</td>
</tr>
<tr>
  <td>Android version/OS</td><td>Nougat 7.0</td>
</tr>
</table>

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by liveHarshit** [comment]
Check Eventbrite
