### ISSUE TITLE
App crashes on search in debug build

### ISSUE THREAD

**Issue by tronku** [fossasia/open-event-attendee-android#2423]
**Describe the bug**
In debug build only, the app crashes on searching for an event. App working properly in release build. 

**Expected behavior**
There should be no crashes while searching.

**Logs**
It's a simple issue related to Fragment's lifecycle.
![Screenshot (37)](https://user-images.githubusercontent.com/31654207/68672685-20a32a80-0578-11ea-9310-f471f057763f.png)

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Mi Note 5 |
|Android Version|  Oreo 8.1  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by tronku** [comment]
I would like to work on this issue.

**Comment by liveHarshit** [comment]
Fixed in PR #2418 
Update your branch with the latest commits on development.
