### ISSUE TITLE
First Name should be a compulsory field

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-attendee-android#2430]
**Describe the feature you'd like**
First name should be made compulsory in the app as there is no name displaying while booking tickets "after Hello" and many other other parts of the app, Or it should display "Hello User" if First and Last Name are null.

**Screenshots**
![event1](https://user-images.githubusercontent.com/44086235/68946665-893d1200-07d9-11ea-857c-c17992d138d4.jpeg)
![event2](https://user-images.githubusercontent.com/44086235/68946669-8b9f6c00-07d9-11ea-979e-20821c47d4a3.jpeg)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
There is a difference between user account and attendee form
