### ISSUE TITLE
INR Currency support

### ISSUE THREAD

**Issue by NishithP2004** [fossasia/open-event-attendee-android#2444]
**Describe the feature you'd like**

It would be great if the currency could be in terms of INR as well since most of the attendees will be from India.
I'm aware that the currency value varies on a daily basis but it would be great if this feature can come into existence.
**Screenshots**

![Screenshot_2019-12-03-22-32-00-261_com eventyay attendee](https://user-images.githubusercontent.com/34577844/70072563-3ce93300-161d-11ea-9d7b-6790d693ccd8.jpg)

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
It is according to the organizer. Try to create an event with INR currency.

**Comment by NishithP2004** [comment]
> It is according to the organizer. Try to create an event with INR currency.

Thanks, I wasn’t aware of that.
