### ISSUE TITLE
Profile UI design improvement

### ISSUE THREAD

**Issue by NishithP2004** [fossasia/open-event-attendee-android#2445]
**Describe the feature you'd like**

For such a great main UI design in the app, the UI design of the profile section looks kind of simple.
It would be great if the design can be made more complex or decorative.
**Screenshots**

![Screenshot_2019-12-03-22-41-20-309_com eventyay attendee](https://user-images.githubusercontent.com/34577844/70073156-635b9e00-161e-11ea-9d65-77062fc1dc62.jpg)

**Additional context**

The UI design of the other sections were great.
**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
Always add screenshot of what you're proposing

**Comment by sdew021** [comment]
@iamareebjamal i would like to take up this issue and start working on it

**Comment by iamareebjamal** [comment]
This is not a valid issue

**Comment by sdew021** [comment]
oh ok
