### ISSUE TITLE
No events available in some regions

### ISSUE THREAD

**Issue by Hasala123** [fossasia/open-event-attendee-android#2447]
There do not seem to be any events loaded up for some regions. (I'm from Sri Lanka, and there is absolutely nothing in the events section). Maybe importing data from these sites can be useful;
  https://10times.com/colombo-lk
  https://www.event.lk/
  https://www.444.lk/events
  https://www.yamu.lk/events
  https://allevents.in/colombo/all

![7e879ae4-0fa9-459d-a4fc-ba562d894772](https://user-images.githubusercontent.com/40402258/70105918-4b107100-1668-11ea-88c6-40111fec86d1.jpg)

**Comment by liveHarshit** [comment]
Go through README
