### ISSUE TITLE
Cannot detect my location.

### ISSUE THREAD

**Issue by varungazala16** [fossasia/open-event-attendee-android#2448]
**Describe the bug**
I installed the open event attendee android app on my phone and when i clicked on open, there was an option of 'detect my location' and to manually write the name of the city or town in which I am currently living. When I clicked on detect my location,it showed a message that it cannot fetch my location. 

**Expected behavior**
 I expected that the app would detect my location automatically and it would work smoothly meeting up my expectations. The commands given by me would be done accurately and in a short interval of time. 

**Screenshots**
[Doc116.pdf](https://github.com/fossasia/open-event-attendee-android/files/3920148/Doc116.pdf)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Redmi note 4] |
|Android Version| 7.0]    |

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
Attach GIF

**Comment by dheerajkotwani** [comment]
working fine for me on same device.

**Comment by akonic** [comment]
can i work on this issue @varungazala16 ?

**Comment by Neilblaze** [comment]
yea same thing happened for me too, I tested it upon my two smartphones having android versions 9.0 (Realme 5pro) and 7.0 (Redmi note4) and for both the system same thing occured!

**Comment by ajax-07** [comment]
If it this issue is still open may i work on it ?
