### ISSUE TITLE
In use my current location, Specify city name instead of state

### ISSUE THREAD

**Issue by PRITI24** [fossasia/open-event-attendee-android#2449]
In use my current location option, Specify city name instead of state. Also It would be easy, if the range of area will be provided for user in which he/she wants to see events. 

![Screenshot_2019-12-04-11-48-52-287_com eventyay attendee](https://user-images.githubusercontent.com/42322432/70117904-a7858780-168c-11ea-9f61-9ff3117ce598.jpg)
.

Please let us know if you can work on it or the issue should be assigned to someone else. 
- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
We are following Eventbrite and using the admin area accordingly.
