### ISSUE TITLE
Error at search events

### ISSUE THREAD

**Issue by Mister-Casper** [fossasia/open-event-attendee-android#2450]
When i open the search tab , search events ,changing location , search stops working

1. Go to the search tab
2. Click on Search for..
3. Enter any text and search
4.Click top right button
5.Chang location
6.Click on the checkmark.
7. Error . Loop animation . search not work.

I was expecting to be able to search for events in a new location.

![Screenshot_20191204-155754](https://user-images.githubusercontent.com/44705397/70128218-12e05100-16af-11ea-9e7b-ee1fd5b6d3ba.jpg)
![Screenshot_20191204-155810](https://user-images.githubusercontent.com/44705397/70128275-24c1f400-16af-11ea-9759-f7d0a55cbb82.jpg)
![Screenshot_20191204-160111](https://user-images.githubusercontent.com/44705397/70128486-7ec2b980-16af-11ea-9ff6-d4b99b1609bb.jpg)
![Screenshot_20191204-155817](https://user-images.githubusercontent.com/44705397/70128497-85513100-16af-11ea-94d3-067d86e341b5.jpg)
![Screenshot_20191204-155829](https://user-images.githubusercontent.com/44705397/70128510-8e420280-16af-11ea-9ac1-b76cae355da7.jpg)
![Screenshot_20191204-154237](https://user-images.githubusercontent.com/44705397/70128538-9ac65b00-16af-11ea-87b6-af445832cac9.jpg)
![Screenshot_20191204-154305](https://user-images.githubusercontent.com/44705397/70128572-a74ab380-16af-11ea-8d62-db8cb5556a14.jpg)
![Screenshot_20191204-154313](https://user-images.githubusercontent.com/44705397/70128579-ac0f6780-16af-11ea-9f06-d8a5710e91d2.jpg)

Device  huawei nova 2i
android 9

Would you like to work on the issue?
No

**Comment by liveHarshit** [comment]
Attach GIF for what you are talking about.

**Comment by uditha-anuranjana** [comment]
is this still open?

**Comment by iamuditha** [comment]
@liveHarshit  is this issue closed ?
