### ISSUE TITLE
Improvement: A more robust data for the Events API

### ISSUE THREAD

**Issue by felixfavour** [fossasia/open-event-attendee-android#2452]
There are no events recognized by the app in my area, I believe if the app can track events in more regions, the growth of this app's users will be exponential. Hence, a greater number of people are assisted in organizing and planning events **in their location**.

**Screenshot**
![Screenshot_20191205-020329](https://user-images.githubusercontent.com/46944485/70194727-b5c2ba80-1703-11ea-85e0-79a7ce800d7b.png)

**Comment by iamareebjamal** [comment]
This is not an issue of the Android app
