### ISSUE TITLE
Can't detect events

### ISSUE THREAD

**Issue by chamodperera** [fossasia/open-event-attendee-android#2454]
### **[Can't detect events on the app]**
**When I go to the website it shows the events going to held**
![Screenshot_20191206-092458 1](https://user-images.githubusercontent.com/39716499/70295224-3cfb5580-180c-11ea-86c5-958b69bebcae.png)

**But in the app nothing shows**

![Screenshot_20191206-092121 1](https://user-images.githubusercontent.com/39716499/70295301-88adff00-180c-11ea-8b27-04cb98a89267.png)
![Screenshot_20191206-092206 1](https://user-images.githubusercontent.com/39716499/70295317-96638480-180c-11ea-9fa7-e4fdb2ad850b.png)

**I also searched by next month.Because the event is on next month.It doesn't even work.**

![Screenshot_20191206-092615 1](https://user-images.githubusercontent.com/39716499/70295428-ffe39300-180c-11ea-8339-150f45251d28.png)

**Location- Sri Lanka**

**Comment by iamareebjamal** [comment]
Search is not that advanced. You have to search in Colombo

**Comment by iamareebjamal** [comment]
If you want to open an issue. Please see if it can be done on eventyay.com or not. If it can't be done on eventyay.com, it's not a bug in app, it's a bug in the system
