### ISSUE TITLE
Bold Or Highlight The Word Privacy Policy 

### ISSUE THREAD

**Issue by aditiverma403** [fossasia/open-event-attendee-android#2455]
While Creating Account, No One Will Understand That Here Is The Link To Click & View Privacy Policies. So,Kindly Fix It Out.
![Screenshot_20191206-114138](https://user-images.githubusercontent.com/58584622/70301189-b6507380-181f-11ea-8d29-60c4b0106800.jpg)

**Comment by iamareebjamal** [comment]
![](https://dl3.pushbulletusercontent.com/BwDyxJJkaoNNwhSgXkUP3p0EhoUQ62AN/Screenshot_20191206-120232.png)

It's a problem of your device

**Comment by aditiverma403** [comment]
Since, you are creating the app for allkind of smartphone users so, these things you must have to keep in mind & kindly resolve the issues that I have faced while using it.
Thank You!!!

**Comment by iamareebjamal** [comment]
It's impossible to control your phone's theme and settings. It's like throwing your phone against a rock and saying that it's an app's problem that the screen is shattered
