### ISSUE TITLE
Add a signup button

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/open-event-attendee-android#2457]
**Describe the feature you'd like**
Add a signup button to the login page.
And add signup with Gmail and FB

**Screenshots**
![1](https://user-images.githubusercontent.com/33794760/70332994-a9a43d80-1868-11ea-9f0a-f92f17607a0f.jpeg)

**Would you like to work on the issue?**
- [ ] Yes
- [x] No
- Other:

**Comment by liveHarshit** [comment]
Enter your email and proceed further.
