### ISSUE TITLE
App stuck on Loading screen after logging out and logging in again

### ISSUE THREAD

**Issue by prakhargurunani** [fossasia/open-event-attendee-android#2458]
**Describe the bug**
After logging out and clearing the app from recent apps, unable to log in again as the app does not move forward from loading screen.

**To Reproduce**
1. Open app and log out
2. Clear app from recent apps
3. Open app again
4. Login screen does not load and app is stuck at the splash screen

**Expected behavior**
A fix ASAP by OpenSource developers or by @fossasia team.

**Logs**
Somewhat similar to #1829 

**Screenshots**

![Screenshot](https://i.imgur.com/XcCTVLt.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi 3S: Lineage OS 15.1|
|Android Version|Oreo 8.1|

**Would you like to work on the issue?**

- [ ] Yes
- [X] No
- Other:

**Comment by iamareebjamal** [comment]
Not reproducible. And not similar to #1829 

This does not look like a crash. Provide more info and reproducible steps

**Comment by ShridharGoel** [comment]
@prakhargurunani Please add a GIF.

**Comment by dheerajkotwani** [comment]
Working fine for my device..

**Comment by reliscu** [comment]
I am experiencing this issue with a Galaxy S8.
