### ISSUE TITLE
The location isn't working properly.

### ISSUE THREAD

**Issue by pq4u** [fossasia/open-event-attendee-android#2459]
The location isn't working properly. It only detects the province in which I live. I live in Poland.

My device: Motorola Moto E5
Android Oreo 8.0
![5757565082796032_1575648219_Screenshot_20191206-170103_1](https://user-images.githubusercontent.com/45707808/70374484-00565980-18f3-11ea-84f5-75ac2343e66e.png)

**Comment by iamareebjamal** [comment]
It is made to detect the province. What else do you want to detect?

**Comment by paweltesny19** [comment]
I thought it would be possible for the city to appear if you could enter it manually.

**Comment by iamareebjamal** [comment]
It is

**Comment by dheerajkotwani** [comment]
@iamareebjamal Can I work on it, to make it display the city name. As I live in noida and when I click on detect location it displays Uttar Pradesh.

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by rasacharjee** [comment]
As it is still detecting the province,can i work on the issue.

**Comment by liveHarshit** [comment]
@rasacharjee please go ahead

**Comment by rasacharjee** [comment]
Thanks, I am figuring out the codebase and will soon make changes to resolve this issue

**Comment by ManishPanwar556** [comment]
can I work on this issue @liveHarshit
