### ISSUE TITLE
Fab icon size changes after feedback

### ISSUE THREAD

**Issue by tronku** [fossasia/open-event-attendee-android#2460]
**Describe the bug**
On Event detail screen, after focusing on feedback edittext view, the size of the fab icons increases in similar events section.

**To Reproduce**
1. Go to Event detail screen
2. Click on 'Write Feedback'
3. Focus on the edittext
4. Dismiss the dialog and notice the change in size of the fab icons.

**Expected behavior**
The size should remain same.

**Screenshots**

![ezgif-6-bf3c159515bc](https://user-images.githubusercontent.com/31654207/70377294-0111de80-1939-11ea-9d77-b30387eee04c.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Mi Note 5 |
|Android Version|  Oreo 8.1  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by tronku** [comment]
I would like to work on the issue.

**Comment by liveHarshit** [comment]
> I would like to work on the issue.

Go ahead.
