### ISSUE TITLE
Notification Bell Badge 

### ISSUE THREAD

**Issue by me-AC** [fossasia/open-event-attendee-android#2462]
**Describe the bug**
On the home page of app, after login the notification button shows the red badge and when you open it there are no notifications. It ALSO happens when you change the city.

**To Reproduce**
*Login is REQUIRED*
1- After logging in the first time it shows the bug.
2- Change the city. It shows it again.
3- Clear app data in settings. Log in again. It shows it again.

**Expected behavior**
It should have shown only when there is a notification. Neither on log in nor on City change

**Logs**
N/A

**Screenshots**
![Screenshot_20191207-220216_Eventyay Attendee](https://user-images.githubusercontent.com/58519437/70378015-7aadca80-1941-11ea-93a3-68432c010325.jpg)
![Screenshot_20191207-220222_Eventyay Attendee](https://user-images.githubusercontent.com/58519437/70378026-a8930f00-1941-11ea-91aa-9a6f11116db6.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung A9 2018|
|Android Version|Android Pie [9.0]|

**Additional context**
N/A

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by tronku** [comment]
#2357 are you referring to this issue?

**Comment by iamareebjamal** [comment]
Yes

**Comment by tronku** [comment]
After the PR #2379 i haven't noticed such issue on the app.

**Comment by iamareebjamal** [comment]
Duplicate of #2357
