### ISSUE TITLE
Make instructions more clear

### ISSUE THREAD

**Issue by aayanraja210** [fossasia/open-event-attendee-android#2463]
**Hard to know what to do, needs a brief tutorial or help section. I personally took a while to realize i needed developermofe to use it properly**

**Would you like to work on the issue**

- [x] No
-

**Comment by iamareebjamal** [comment]
Developer mode is for developer-only features which are either not tested or incomplete and you definitely don't need developer mode to use it properly. 

Secondly, bugs related to features enabled by developer mode will be considered extremely low priority anyway.

Lastly, this is not a feature we want people to use. So, only a developer wanting to work on an issue related to the hidden features should be able to use them
