### ISSUE TITLE
Not returning results for location search

### ISSUE THREAD

**Issue by aayanraja210** [fossasia/open-event-attendee-android#2464]
**Issue**
Trying to find a location while creating an event, but it returns no result. Locations are not found
**Steps to reproduce the behavior:
1. Go to 'Live page'
2. Click on 'Plus FAB'
3. Scroll down to 'Location Details'
4. Click on 'Search Bar'
5. Search for a location
6. See error -->

**Expected Behaviour**
Expect to get a list of locations when searching for them.

**Logs**
N/A

**Screenshots**
![Screenshot_20191207-131758](https://user-images.githubusercontent.com/50059339/70379069-4365fc00-18f6-11ea-940d-196c5b030335.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Samsung S8 |
|Android Version| 9     |

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by iamareebjamal** [comment]
Google Maps is not working. Please install dev version to get the latest code, where MapBox is used
