### ISSUE TITLE
Location issue

### ISSUE THREAD

**Issue by Coder-Ops415** [fossasia/open-event-attendee-android#2466]
**Describe the bug**

When location of the event is viewed ot redirects to google maps where the location is preset to 0,0 latitude and longitude
**To Reproduce**

1.go to fossasia app
2.click on any event
3.view location of the event
4.it will redirect to google maps where location is not shown there is some other random location and not of the event

**Expected behavior**

**Logs**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |redmi 5 plus|
|Android Version|Oreo 8.1   |
**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [•] No

**Comment by iamareebjamal** [comment]
Google Maps are not working. Build and install latest app from the repo
