### ISSUE TITLE
Old events are still Published

### ISSUE THREAD

**Issue by Aryan-401** [fossasia/open-event-attendee-android#2467]
**Describe the bug**
Whenever looking for an event, it shows a wrong location

**To Reproduce**
1. Click on "Search" in the bottom navbar
2.Click the "In" dialog box
3.Type "Delhi"
**Expected behavior**
Shouldn't show events which are expired
**Logs**
No logs available

**Screenshots**
https://lh3.googleusercontent.com/iLDpKHLRIIbYYnxxzHKvwP6QeUQXnzo73U_u92s4XjBCGUqe_ajmD2bgi9GNdLgofVA0LPySmG1Xzp4RyVgNnogk7K67E9jOeZYSD--VKvAJ7dtm7pqt_OJnHH_9Rt6ojS6FCRrYMS0NIkG-yNojlMYP0ZZBf1SGbSzRxD9ol6UxLSr765n36UW0PTRLZTXRA-Yz0EPlsqgCRTYUelfq5e9jeCv2VTQplCU3xBfwtuFIag5zNW83i1Ww5vAjxJgf2qdVcQx0owzrSRzgWBpNF0iCVf4imHPKsrQAi2gFInzlvvYu74j1CdLy-nPQZl5IXki5S5YIuamG_jwqUkgukg1RhpX3_z8sXCHenv87Js-b2coNbiO0fFh-nrl8yEJ3Y5PqNqHcnSNRk93K9z-gRhjvx0qo-t3t2HYLXCDyUdgpCID99bXFlormXLqVNjBPbbBcr45egJ5QgPjmMMKRVI7gyodgG-oFczUI3vknDnZyFi1Jn6S0qKyg8rxwQan6SgvGPEWe-pgC0nutPERS6SblXmsAKjnzmfWIVjwDYpFcmLdqDe1l-Qgf82czUBLIYv3XvXzqYOOSPvk0uP3p5ZZjn8m-wYcPG47_EOp58Hj0zOp6fCUOziXsL-8ALlvKdnkpRiYuGMb8kGYHQSLUoWJzLCZUn4X1PR2Jjm8pMainK2S1CusnchY=w846-h1830-no
**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Realme 2 Pro |
|Android Version |  Pie 9.0|

**Additional context**
Past events shouldn't be part of the app as it can seriously confuse the person
**Would you like to work on the issue?**

- [ ] No

**Comment by codedsun** [comment]
This is not an expired event.

https://eventyay.com/e/77a533b1

**Comment by codedsun** [comment]
This is not an expired event @Aryan-401 

https://eventyay.com/e/77a533b1

It's of 2020
