### ISSUE TITLE
"Enter Location" recyclerview margin from bottom

### ISSUE THREAD

**Issue by VarunSaini23** [fossasia/open-event-attendee-android#2470]
**Describe the bug**
The recyclerview in "Enter location" is not having proper margins from the bottom which make it look not so good.
**To Reproduce**

**Screenshots**

![WhatsApp Image 2019-12-10 at 12 01 41 AM](https://user-images.githubusercontent.com/40406851/70462238-8257a580-1ae0-11ea-8406-b069ed143492.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |[Redmi Note 5]|
|Android Version            |[Oreo 8.1 |

**Additional context**

**Would you like to work on the issue?**

- [✓] Yes
- [ ] No
- Other:

**Comment by VarunSaini23** [comment]
@iamareebjamal I want to fix this bug. Please assign it to me.

**Comment by iamareebjamal** [comment]
Send a PR, no need for assignment
