### ISSUE TITLE
Dark Mode feature 

### ISSUE THREAD

**Issue by MuhammadWasif** [fossasia/open-event-attendee-android#2475]
The app is jusg awesome but it would be great to have a feature of **Dark Mode** in the app.
Enabling the mode will change the theme of app. User could change mode from the **drawer** using a switch button
Are you working on this?
No, I'm not an android developer. So it would be great if an android dev. works on this feature

**Comment by refactor-droidyy** [comment]
@MuhammadWasif can I work on this issue

**Comment by iamareebjamal** [comment]
Very low priority. We cannot maintain dark mode when basic features of app are not working

**Comment by MuhammadWasif** [comment]
@refactor-droidyy yeah! Why not?

**Comment by iamareebjamal** [comment]
> Why not?

The reason is given above

**Comment by VinamraGuptaa** [comment]
Hey. Is this issue still open?
