### ISSUE TITLE
UI- Forgot-password_notification

### ISSUE THREAD

**Issue by PicantaData** [fossasia/open-event-attendee-android#2476]
1. When we press "I forgot my password" in login there is no pop-up notification regarding the password reset link sent to the respective email id.

To Reproduce the first bug;
1. Go to 'Profile'
2. Click on 'login'
3. Enter the registered email and continue
4. See error -->When you press "I forgot my password, it shows loading and no notification 
    appears regarding the reset link sent.

**Expected behavior**
We expect a notification saying that "A reset link has been sent to your respective e-mail"

**Screenshots**
![Screenshot_bug1](https://user-images.githubusercontent.com/58455626/70506899-56c0d380-1b51-11ea-9796-06adff8f8885.png)

**Smartphone Info:**
|Device         |Redmi Note-5 Pro|
|Android Version|Android-10|

**Would you like to work on the issue?**
- [No]

**Comment by iamareebjamal** [comment]
Please raise 3 separate issues for 3 bugs

**Comment by tronku** [comment]
I would like to work on these bugs.

**Comment by tronku** [comment]
On clicking the forgot my password, I am receiving the reset mail but app's showing "Email address not present in the server" error.

**Comment by iamareebjamal** [comment]
Paste the response from the server

**Comment by tronku** [comment]
<title>429 Too Many Requests</title>
<h1>Too Many Requests</h1>
<p>Limit for this action exceeded</p>

**Comment by tronku** [comment]
Another response is this - 
{
  "email": "shubham.pathak2000@gmail.com", 
  "message": "If your email was registered with us, you'll get an                          email with reset link shortly"
}

There is a check of message == "Email sent" in the app which shows that mail has been sent to you on clicking the forgot password. But as the message is different in case of success, no message is displayed to the user. If the forgot password is clicked more than one time during a short time  period, too many request error occur and "Email address not present" message is displayed.

**Comment by tronku** [comment]
@iamareebjamal what should i do to fix this? Will, there be any change from the server response or should i handle it from the app side?

**Comment by iamareebjamal** [comment]
> There is a check of message == "Email sent" in the app which shows that mail has been sent to you on clicking the forgot password. But as the message is different in case of success, no message is displayed to the user.

Obviously that's app's problem. What can server do in this regard?
