### ISSUE TITLE
UI-Icon overlapping header

### ISSUE THREAD

**Issue by PicantaData** [fossasia/open-event-attendee-android#2479]
1. The icon of the ticket overlaps the violet-colored header of the page.

To Reproduce the bug:-
1. Go to the tickets section.
2. See error-->When you have no ticket history, the icon overlaps the violet-colored header.

**Expected Behaviour**
Shift the alignment a little down

**Screenshots**
![Screenshot_20191210-090321](https://user-images.githubusercontent.com/58455626/70506966-72c47500-1b51-11ea-82fe-f68856b5f970.png)

**Smartphone Info:**
|Device         |Redmi Note-5 Pro|
|Android Version|Android-10|

**Would you like to work on the issue?**
- [No]

**Comment by PRITI24** [comment]
I would like to work on this issue
