### ISSUE TITLE
UI-Icon of Events overlapping the screen

### ISSUE THREAD

**Issue by PicantaData** [fossasia/open-event-attendee-android#2480]
1. When the page of the Events is refreshed, the icon of the calendar comes over the screen.

To Reproduce the bug;
1. Go to the events section from the navigation bar.
2. Refresh the screen by pulling down the window.
3. See Error-->You will see the icon of Events coming over the content.

**Screenshots**

![Screenshot_20191210-110928](https://user-images.githubusercontent.com/58455626/70506989-7c4ddd00-1b51-11ea-86c7-a693d3c5fda4.png)

**Smartphone Info:**
|Device         |Redmi Note-5 Pro|
|Android Version|Android-10|

**Would you like to work on the issue?**
- [No]

**Comment by tronku** [comment]
I would like to work on this

**Comment by liveHarshit** [comment]
Go ahead
