### ISSUE TITLE
Unable to view Notifications on the App

### ISSUE THREAD

**Issue by aryanguls** [fossasia/open-event-attendee-android#2481]
**Describe the bug**
The Eventyay Attendee App shows a notifications option on the top right corner but in the case of notifications being there i am unable to view them on opening the notifications tab.(screenshots provided)

**To Reproduce**
1. Go to the Eventyay Attendee App
2. On opening the app press the bell icon on the top left corner 
3. In case it has a red dot on it it still will not display notifications(screenshots provided).

**Expected behavior**
On pressing the bell icon i expected to see all the recent/unread notifications.

**Screenshots**
![Screenshot_2019-12-10-15-55-21-682_com eventyay attendee](https://user-images.githubusercontent.com/58459496/70522087-71517780-1b66-11ea-90b8-6a9092192b13.jpg)
![Screenshot_2019-12-10-15-55-21-682_com eventyay attendee_2](https://user-images.githubusercontent.com/58459496/70522066-6860a600-1b66-11ea-99ee-eef4518bbdd3.jpg)
![Screenshot_2019-12-10-15-55-35-760_com eventyay attendee](https://user-images.githubusercontent.com/58459496/70522093-744c6800-1b66-11ea-857d-49cf2dba1d1f.jpg)
![Screenshot_2019-12-10-15-55-31-852_com eventyay attendee](https://user-images.githubusercontent.com/58459496/70522099-79a9b280-1b66-11ea-8704-3c51c03341f5.jpg)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
Dupolicate of #2357

**Comment by aryanguls** [comment]
Sorry but I didn't see the other issues. My mistake. Thank you.
