### ISSUE TITLE
App crash on clicking skip

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-attendee-android#2482]
App crashes on pick a city screen and `Skip` is clicked. On opening again, home screen loads but crashes on clicking search or login

Basically, app is in unusable state

**Comment by adityastic** [comment]
I would like to work on it

**Comment by tronku** [comment]
Can you add the screenshots? I am not facing any issue on pick city screen.

**Comment by iamareebjamal** [comment]
On which app version are you?

**Comment by tronku** [comment]
Latest one - 0.9.0

**Comment by iamareebjamal** [comment]
Have you logged out and tried again. Clear app data and check. It's crashing for me on tickets, favorites, login and skip

**Comment by codedsun** [comment]
Not crashing for me, can you tell me your Android Version @iamareebjamal ?

**Comment by iamareebjamal** [comment]
Crashing on all versions - 5, 6, 7, 7,1, 8, 8,1, 9
Devices - Huawei P8 Lite, Mate 9, Moto G4, Moto Z, Galaxy S9, Pixel 1, Pixel 2, Pixel 3, Nokia 1

```
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
```

**Comment by iamareebjamal** [comment]
It's because of this:

https://github.com/fossasia/open-event-attendee-android/blob/989c8f1/app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt#L53-L60

**Comment by tronku** [comment]
working on the issue
