### ISSUE TITLE
UI-False Notification indication

### ISSUE THREAD

**Issue by PicantaData** [fossasia/open-event-attendee-android#2485]
False Notification dot

**To Reproduce**
1. See error -->When Events page is refreshed we see a new notifications for us(by red light indicator). But when it is opened, there is no new notification.

**Expected behavior**
Notification dot should appear for new notifications.

**Screenshots**
![Screenshot_20191210-205102~2](https://user-images.githubusercontent.com/58455626/70543571-9bb82a80-1b90-11ea-8350-302a32ab0cd8.png)
![Screenshot_20191210-205112](https://user-images.githubusercontent.com/58455626/70543573-9bb82a80-1b90-11ea-99d5-77e6a396d9a3.png)

**Smartphone Info:**
|Device         |Redmi Note-5 Pro|
|Android Version|Android 10|

**Would you like to work on the issue?**
- [ No]

**Comment by iamareebjamal** [comment]
Please don't open duplicate issues

**Comment by iamareebjamal** [comment]
Duplicate of #2357
