### ISSUE TITLE
Move search result observer to onCreateView

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-attendee-android#2487]
https://github.com/fossasia/open-event-attendee-android/blob/99d61f40bab989c6e8de5770861c093cd710e7ea/app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt#L79-L83

**Comment by codedsun** [comment]
I am taking this up.

**Comment by iamareebjamal** [comment]
Beginners

**Comment by refactor-droidyy** [comment]
@iamareebjamal can i work on this ?

**Comment by codedsun** [comment]
@refactor-droidyy Yes you can!
