### ISSUE TITLE
Reloading the events tab

### ISSUE THREAD

**Issue by me-AC** [fossasia/open-event-attendee-android#2498]
**Describe the bug**

On reloading the events tab, it first loads the screen, then shows the "Sorry, there are no events available" logo for very short time in center, then the logo shifts down and overlaps the found events and is visible for some time.

**To Reproduce**
1. Go to 'Events tab'
2. Reload the page
3. See the error

**Expected behavior**

It should not show the logo if there are events available.

**Screenshots**

![Screenshot_20191212-193006_Eventyay Attendee](https://user-images.githubusercontent.com/58519437/70719160-7b66a800-1d17-11ea-80f3-7d32252595d4.jpg)
I can't time the screenshot for the first time the error is shown.
You can see the latter part of bug on the bottom of the screen where the logo is overlapping the shown events.
**Smartphone Info:**

|Device         |Samsung A9 2018|
|Android Version|Pie 9.0|

**Would you like to work on the issue?**

NO

**Comment by manan025** [comment]
The error does exists. Please have a look admins.

**Comment by tronku** [comment]
This is same as #2480

**Comment by tronku** [comment]
I would like to work on this.

**Comment by liveHarshit** [comment]
Duplicate
