### ISSUE TITLE
app background not working properly.

### ISSUE THREAD

**Issue by darshk07** [fossasia/open-event-attendee-android#2503]
App background is not full upto the resolution of the phone. 

![5970205251993600_1576255412_Screenshot_2019-12-13-22-12-32-53_a1e480d5f8a68dac724a3f60014ae8f6](https://user-images.githubusercontent.com/40802851/70852544-8f9dd700-1ec8-11ea-83d3-d4229c64d5da.png)
![5970205251993600_1576255412_Screenshot_2019-12-13-22-12-28-07_a1e480d5f8a68dac724a3f60014ae8f6](https://user-images.githubusercontent.com/40802851/70852545-92003100-1ec8-11ea-99e5-9c070bb9837d.png)
![5970205251993600_1576255412_Screenshot_2019-12-13-22-11-28-60_a1e480d5f8a68dac724a3f60014ae8f6](https://user-images.githubusercontent.com/40802851/70852546-93c9f480-1ec8-11ea-8c36-316ebfa06c81.png)

![5970205251993600_1576255416_Screenshot_2019-12-13-22-12-46-73_a1e480d5f8a68dac724a3f60014ae8f6](https://user-images.githubusercontent.com/40802851/70852539-7bf27080-1ec8-11ea-98ef-794b14ba156a.png)

**Comment by adityastic** [comment]
looks like you have override force dark mode ON
