### ISSUE TITLE
Hiding Keyboard on clicking anywhere on SignUp Fragment

### ISSUE THREAD

**Issue by anubhav11march** [fossasia/open-event-attendee-android#2507]
**Describe the bug**
The Keyboard hides only on clicking on back button on the sign up screen. A fix would be to hide the keyboard on clicking anywhere on the screen.

**To Reproduce**
1. Go to Sign up screen
2. Click on FirstName EditText
3. Try hiding the keyboard by clicking elsewhere on the screen.
4. The keyboard doesn't hide and back button or enter needs to be clicked.

**Screenshots**
Notice that back button needs to pressed in order to hide keyboard.
![20191216_033518](https://user-images.githubusercontent.com/42939575/70870101-6eff7b00-1fb5-11ea-9a55-c6d252c23ca4.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Honor 9 Lite|
|Android Version|Oreo 8.1    |

**Would you like to work on the issue?**
YES

**Comment by adityastic** [comment]
This kind of an interaction is used in HIG, and not Material Design. @iamareebjamal should be the right person to make a decision 😉

**Comment by iamareebjamal** [comment]
Agree with @adityastic but here, there is no workaround than to repeatedly tap back button and it gets tedious, hence it is fine. If there is any better suggestion, then we'll implement that
