### ISSUE TITLE
Profile button leads to logout

### ISSUE THREAD

**Issue by manan025** [fossasia/open-event-attendee-android#2512]
**Describe the bug**
The Profile button in the settings makes a dialog which is for logging out an user and I also saw that there is no Logout button so the text might be written wrong.

**To Reproduce**
1. Go to 'Profile section'
2. Click on 'Settings'
3. Click on 'Profile' on the top of account section
4. See error -> 'Are you sure you want to log out?'

**Expected behavior**
There should be a dedicated Logout button and the usage of Profile button should be changed.

**Logs**
N.A.

**Screenshots**

**Smartphone Info:**
|Device         |OPPO REALME 1|
|Android Version| [Oreo 9.0]    |

**Would you like to work on the issue?**
- Yes
- [ ✓ ] No
- Other:

**Comment by refactor-droidyy** [comment]
I want to work on this issue

**Comment by adityastic** [comment]
@refactor-droidyy sure, go ahead

**Comment by refactor-droidyy** [comment]
@adityastic there is no use for profile button(for the purpose of editing profile related details) in Setting Fragment since it is available in ProfileFragment which is better. 
so can I make A PR related the same idea.

**Comment by adityastic** [comment]
@nikit19 @iamareebjamal @liveHarshit would be the right guys to confirm that :)

**Comment by refactor-droidyy** [comment]
@nikit19 @liveHarshit please confirm.

**Comment by liveHarshit** [comment]
> @nikit19 @liveHarshit please confirm.

We're following Eventbrite. Not an issue.
