### ISSUE TITLE
Transition overlaps the design in Tickets tab

### ISSUE THREAD

**Issue by manan025** [fossasia/open-event-attendee-android#2515]
**Describe the bug**
After I go to the Tickets section, I find that the page load transition overlaps the design that is on the top. (Screenshot attached)

**To Reproduce**
1. Go to 'Tickets' section
2. See error

**Expected behavior**
It shouldn't be overlapping the top design

**Logs**
N.A.

**Screenshots**

![Screenshot_2019-12-18-21-05-54-02_a1e480d5f8a68dac724a3f60014ae8f6](https://user-images.githubusercontent.com/40761012/71100471-19a4b300-21db-11ea-9a15-d1a160588dcb.png)

**Smartphone Info:**

|Device         | [Oppo Realme 1] |
|Android Version| [Pie 9.0] |

**Additional context**
I think the error is with any xml design file.

**Would you like to work on the issue?**

- [ - ] Yes
- [ ✓ ] No
- Other:

**Comment by liveHarshit** [comment]
Not an issue
