### ISSUE TITLE
Password minimum length different

### ISSUE THREAD

**Issue by shlokj** [fossasia/open-event-attendee-android#2523]
While entering the password, the error message under the edittext says minimum 6 characters are required. On creating a password of 6 characters, a snackbar message pops up, saying the password should be at least 8 characters long. Suggestions: require the password to be at least 6 characters long, and maintain coherence throughout.

**Comment by refactor-droidyy** [comment]
@shlokj can I work on this.

**Comment by tolstovdmit** [comment]
I think it was fixed in #1889.
