### ISSUE TITLE
Bug report:

### ISSUE THREAD

**Issue by shrel301** [fossasia/open-event-attendee-android#2528]
**Describe the bug**

The application crashes a number of times. In my case, it crashed twice. Once when I tried opening a live event and next when I clicked on the "Share" option.

**To Reproduce**
1. Go to 'menu'
2. Click on 'Share'
3. The app crashes

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |ASUS_X00TD|
|Android Version| PIE 9.0|

The frequency of the crashes are not consistent.

**Would you like to work on the issue?**

- [. ] No

**Comment by tronku** [comment]
Share option is working, not crashing in my case. Can you please share a video or a screenshot?

**Comment by shrel301** [comment]
Yeah sure... here’s the drive link
https://drive.google.com/drive/folders/1-C4g6cTkTz_J0oj-vGNiD7h27BZD5A4t

**Comment by adityastic** [comment]
@shrel301 This might the wrong repository for your crash videos :). You're using the oraganizer app ;)

**Comment by shrel301** [comment]
Oops... So what should I do

**Comment by adityastic** [comment]
@shrel301 github.com/fossasia/open-event-organizer-android should be the place to go ;)

**Comment by shrel301** [comment]
Ohk... Thanks for your help. I'll delete the report.

**Comment by adityastic** [comment]
@shrel301 perfect
