### ISSUE TITLE
Improvements to the reset password page

### ISSUE THREAD

**Issue by arpitaj12** [fossasia/open-event-attendee-android#2530]
Inputs during password reset are vague, and those should be clarified. Also, there is no need to have a  create event button during password reset as it is irrelevant.

**Comment by manan025** [comment]
I would like to work on this issue!

**Comment by manyadua16** [comment]
I am also having the same problem

**Comment by iamareebjamal** [comment]
No context or screenshot. Add screenshots to prevent closing of the issue. As mentioned in #2539 nothing described in the issue matches the UI of app

**Comment by dheerajkotwani** [comment]
@arpitaj12 can you please elaborate the issue
