### ISSUE TITLE
Issue with the share button on the Likes tab in Eventyay

### ISSUE THREAD

**Issue by GamingWithShaurya** [fossasia/open-event-attendee-android#2532]
**Describe the feature you'd like**

When you press the share button, you also have the option to share the event link to apps like games and cash grab apps which is not required and I checked if there is something to even input there but there is no area to input links in games so unnecessary.

**Screenshots**

<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/35957429/71578921-218c1d80-2b20-11ea-9120-8b61a9f49fc3.jpg"></td>
<td><img src="https://user-images.githubusercontent.com/35957429/71578921-218c1d80-2b20-11ea-9120-8b61a9f49fc3.jpg"></td>
<td><img src="https://user-images.githubusercontent.com/35957429/71578923-218c1d80-2b20-11ea-904d-a4a263239aff.jpg"></td>
</tr></table>

**Additional context**

I would recommend to remove them as even if in the background they get the link of our event we planning to visit then it is a little bad for our privacy as they can get an idea where we are.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other: I can work on it if I get to but I don't have too much experience in android coding.

**Comment by iamareebjamal** [comment]
Do you think we have added these apps in the menu? And we can predict what apps user has installed and add those there?
