### ISSUE TITLE
Remove warning in activity_main.xml

### ISSUE THREAD

**Issue by muneebGH** [fossasia/open-event-attendee-android#2534]
**Describe the bug**

Use a layout_height of 0dp instead of @dimen/layout_margin_none for better performance  When only a single widget in a LinearLayout defines a weight, it is more efficient to assign a width/height of 0dp to it since it will absorb all the remaining space anyway. With a declared width/height of 0dp it does not have to measure its own size first.

**To Reproduce**

replace it with 0 dp
<img width="810" alt="Screenshot 2019-12-31 at 12 29 41 AM" src="https://user-images.githubusercontent.com/49611774/71597823-7783b400-2b66-11ea-8a36-668108adf43c.png">

**Expected behavior**

**Logs**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
yes 
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
It is already 0dp. Android Studio is being stupid. Once you change it, it'll give warning that use dimens instead

**Comment by muneebGH** [comment]
ok
