### ISSUE TITLE
Can't find any events in New York City!

### ISSUE THREAD

**Issue by Sam659** [fossasia/open-event-attendee-android#2555]
**Describe the bug**
New York City is a major city with hundreds of events going on daily. However, the application is telling me: "Sorry, there are no events available".

**To Reproduce**

|               | |
|---------------|-|
|Device         Samsung s8
|Android Version| Latest version of Android

**Comment by iamareebjamal** [comment]
That's correct. We can't magically list events happening in New York City. We show the events which are registered on the linked open event server - eventyay.com

So, yeah, sorry, there are no events available in New York in eventyay
