### ISSUE TITLE
UI and Maps Integration Bug

### ISSUE THREAD

**Issue by rmcsitdev** [fossasia/open-event-attendee-android#2565]
In the app, UI needs improvement. And, when we click on a particular event, the integrated map is empty, after tapping on it, Google maps gets opened but the location of the event is not showed.

**Comment by scixor** [comment]
Can I work on this? @iamareebjamal  :)

**Comment by Sid911** [comment]
I don't think there is a problem with maps.... its just that the map is not hidden if the field is empty
