### ISSUE TITLE
Clicking on profile button prompts to log out

### ISSUE THREAD

**Issue by scixor** [fossasia/open-event-attendee-android#2572]
**Describe the bug**
The "profile" button prompts to log user out
**To Reproduce**

1. Login into eventyay
2. Go to profile option 
3. under **General**  go to settings 
4. Click on profile
**Expected behavior**
It should be edit profile or should bring back to profile page

**Screenshots**

![Screenshot_20200118-151921](https://user-images.githubusercontent.com/27860105/72661957-c2c31100-3a06-11ea-921f-63f0e1d8a656.png)
![Screenshot_20200118-151926](https://user-images.githubusercontent.com/27860105/72661958-c3f43e00-3a06-11ea-92a2-88d1d9618109.png)

**Smartphone Info:**
Device : Asus Zenfone Max Pro m1
Android Version: Pie 9 

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by iamareebjamal** [comment]
Duplicate
