### ISSUE TITLE
Chore: Upgrade Dependencies and sdk version

### ISSUE THREAD

**Issue by scixor** [fossasia/open-event-attendee-android#2584]
**Describe the chore**
Upgrade the dependecy of stripe etc. and also upgrade the targetsdkversion and compiled version to 29 (google recommends doing this)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by adityastic** [comment]
We already have dependabot to update our dependencies

**Comment by scixor** [comment]
@adityastic still there are dependencies not updated 😅 and being ignored by dependabot
