### ISSUE TITLE
Entering username instead of links instead of links in profile edit

### ISSUE THREAD

**Issue by scixor** [fossasia/open-event-attendee-android#2591]
**Describe the issue**
This isn't really a bug but is a user clarification issue, currently in edit profile page, the user needs to enter the entire link with the protocol itself like `https` etc. which is tiresome to add in mobile as people using instagram in mobile probably use it in instagram app, not to mention chromium engines are now not showing the protocols in the address bar in general. This led to some of the issues like.

https://github.com/fossasia/open-event-attendee-android/issues/2524
https://github.com/fossasia/open-event-attendee-android/issues/2526
https://github.com/fossasia/open-event-attendee-android/issues/2525

**Expected behavior**
User Should be able to just type the username instead of the link

**Would you like to work on the issue?**
- [ ] Yes
- [x] No
- Other:

**Comment by iamareebjamal** [comment]
And how will we convert it to links?

**Comment by scixor** [comment]
@iamareebjamal just add a header to it like a username is always `https://www.instagram.com/ + <username>`

**Comment by scixor** [comment]
same can be done by retrieving entire link and then cutting off the header part in loading part 
`https://www.instagram.com/<username>`  to get `<username>`

**Comment by iamareebjamal** [comment]
OK, what if someone enters `@iamareebjamal`

**Comment by scixor** [comment]
I think we have to trim the string anyways.. for spaces we can remove other literals like `@`

**Comment by iamareebjamal** [comment]
OK, what is some user's username itself has `@` at start

**Comment by scixor** [comment]
@iamareebjamal not possible. because while creating account in any platform you cannot add `@` as it is notifier for tagging inside username... think if you could tag a person with @ <@username>

**Comment by iamareebjamal** [comment]
In any platform?

**Comment by scixor** [comment]
I mean in the platforms we are having .. in twitter facebook and Instagram

**Comment by iamareebjamal** [comment]
Then go ahead, and write tests for the same

**Comment by scixor** [comment]
tests? did last one had tests @iamareebjamal for it

**Comment by iamareebjamal** [comment]
No

**Comment by scixor** [comment]
@iamareebjamal are there any tests in the application?

**Comment by scixor** [comment]
I just see 1 with deprecated popups all over it

**Comment by iamareebjamal** [comment]
Don't know what you mean by that

**Comment by scixor** [comment]
oh sorry .. I saw just one test, in androidTests folder which probably had
an example instrumentation test

**Comment by scixor** [comment]
Anyone else can look into this!
