### ISSUE TITLE
Search text overflows in the search field

### ISSUE THREAD

**Issue by insaiyancvk** [fossasia/open-event-attendee-android#2592]
**Describe the bug**
The text in the text field for searching the location overflows when many characters are input.

**To Reproduce**

1. Go to the app
2. Click on text field under "what's good in"
3. Enter a large number of characters.
4. The text overflows.

**Expected behavior**
All the text will be visible in the text field.

**Screenshots**
![bug](https://user-images.githubusercontent.com/53230977/72904984-c7b0f900-3d55-11ea-878a-53fc89d45135.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 7|
|Android Version| 9 (Pie) |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by insaiyancvk** [comment]
> **Describe the bug**
> The text in the text field for searching the location overflows when many characters are input.
> 
> **To Reproduce**
> 
> Device	Redmi Note 7
> Android Version	9 (Pie)
> **Would you like to work on the issue?**
> 
> * [x]  Yes
> * [ ]  No

**Comment by iamareebjamal** [comment]
Always add screenshots

**Comment by ankushmundhra** [comment]
@insaiyancvk Is this issue solved? Can i work on this?

**Comment by insaiyancvk** [comment]
@ankushmundhra I am working on this.

**Comment by rob729** [comment]
@insaiyancvk  Are you working on this issue?
