### ISSUE TITLE
Accepts phone numbers more than 10 digits in profile settings

### ISSUE THREAD

**Issue by insaiyancvk** [fossasia/open-event-attendee-android#2595]
**Describe the bug**
A phone number of more than 10 digits is accepted in profile settings.

**To Reproduce**
1. Click Profile then edit profile.
2. Enter a phone number with greater than 10 digits.
3. Click on update and the settings are accepted.

**Expected behaviour**
1. A limit of 10 digits is added to the existing text field.
2. Add a spinner so that the user chooses the country code.

**Screenshots**
![bug](https://user-images.githubusercontent.com/53230977/72915149-d9020180-3d65-11ea-96ad-0aa5914d7105.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Redmi Note 7 |
|Android Version| 9 (Pie)  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by insaiyancvk** [comment]
@iamareebjamal Shall I add a spinner so that user can select their country code? or a text field for the user to enter the country code manually?

**Comment by iamareebjamal** [comment]
Spinner

**Comment by ankushmundhra** [comment]
@insaiyancvk Is someone working on this ?

**Comment by insaiyancvk** [comment]
@ankushmundhra yes, I am working on this.

**Comment by rob729** [comment]
@insaiyancvk Are you still working on this issue?

**Comment by insaiyancvk** [comment]
@rob729 I am working on the spinner part now

**Comment by kusoz5** [comment]
can i work over this issue?

**Comment by rasacharjee** [comment]
I am interested to work on the issue. If possible please assign the issue to me.

**Comment by liveHarshit** [comment]
@kusoz5 Go ahead but follow the comments here https://github.com/fossasia/open-event-attendee-android/pull/2617, thanks

**Comment by ManishPanwar556** [comment]
Can I work on the spinner issue @liveHarshit

**Comment by shubhamranswal** [comment]
Hello everyone, is this issue still open? I am a beginner and want to contribute. 
@liveHarshit

**Comment by shankarpriyank** [comment]
I would like to work on this issue
@liveHarshit
