### ISSUE TITLE
bug: Scrolling in Notification Activity

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-attendee-android#2603]
**Describe the bug**
While scrolling in notification activity the layout overlaps on Unread and All button on the top

**To Reproduce**
1. Go to Notification
2. Check if there are some notifications present
3. Scroll down

**Expected behavior**
The layouts should not overlap over the buttons

**Screenshots**
![openevent_notification_scroll_bug](https://user-images.githubusercontent.com/44086235/73130774-a33e7080-4024-11ea-826d-7c7d9368246e.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|
|Android Version| Nougat 7.0 |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by ankushmundhra** [comment]
@dheerajkotwani can i work on this?

**Comment by dheerajkotwani** [comment]
okay @ankushmundhra

**Comment by dheerajkotwani** [comment]
I am working on @ankushmundhra
