### ISSUE TITLE
bug: Change password dialog in edit profile

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-attendee-android#2604]
**Describe the bug**
When we open the change password dialog in landscape mode the view gets cut from the button and it does not look properly

**To Reproduce**
1. Go to Edit Profile in landscape mode
2. Click on Change Password
3. Try to scroll

**Expected behavior**
Everything should be visible properly and there should be an option of scrolling

**Screenshots**
![change_pass_dialog_bug](https://user-images.githubusercontent.com/44086235/73130816-91a99880-4025-11ea-9a85-1bf45fcc875b.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|
|Android Version|Nougat 7.0  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by ankushmundhra** [comment]
@dheerajkotwani can i work on this.

**Comment by dheerajkotwani** [comment]
I had already solved this @ankushmundhra
