### ISSUE TITLE
Add ScrollView in SignUp Screen

### ISSUE THREAD

**Issue by AminullahTajMuhammad** [fossasia/open-event-attendee-android#2609]
**Describe the bug**
Add scrollView in the signup screen.

**Expected behavior**
SignUp Button show when android phone keyboard is opened.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | OPPO F7 |
|Android Version| Pie 9 |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by AminullahTajMuhammad** [comment]
@championswimmer Can I work on this issue?

**Comment by dheerajkotwani** [comment]
@AminullahTajMuhammad scroll view is already present in the sign up activity.

**Comment by AminullahTajMuhammad** [comment]
@dheerajkotwani But it's not working on my device.

**Comment by dheerajkotwani** [comment]
@AminullahTajMuhammad this is because the inner layout (linear_layout) inside the scroll layout is set to match_parent height making it to wrap_content can solve this :)

**Comment by AminullahTajMuhammad** [comment]
@dheerajkotwani I had checked it. still, it's not working. Can I do this with a new approach?

**Comment by rcs10** [comment]
@dheerajkotwani @AminullahTajMuhammad  changing the value of WindowSoftInputMode to "adjustResize" in manifestfile did the job.

**Comment by The-Pascal** [comment]
@championswimmer I found the same issue in the app.
If the issue is still open, can I work on it ?

**Comment by kusoz5** [comment]
> **Describe the bug**
> Add scrollView in the signup screen.
> 
> **Expected behavior**
> SignUp Button show when android phone keyboard is opened.
> 
> **Smartphone Info:**
> 
> Device	OPPO F7
> Android Version	Pie 9
> **Additional context**
> 
> **Would you like to work on the issue?**
> 
> * [x]  Yes
> * [ ]  No
> * Other:

Can I work over this issue?

**Comment by liveHarshit** [comment]
PR is already under review for this ticket. @rcs10 Please check comments. thanks

**Comment by ghost** [comment]
Can I work on this issue?
