### ISSUE TITLE
chore: Remove hardcoded strings from xml and Java files 

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-attendee-android#2610]
**Describe the chore**
There are various hardcoded strings present in the code which can be replaced.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by Rita-Okonkwo** [comment]
Hello please has this been taken care of? If no, can I work on it?

**Comment by devptyagi** [comment]
If this one's available, Can I Work on it?

**Comment by Harshit564** [comment]
Yes i will work

**Comment by saketsingh0078** [comment]
is this issue is fix , if no then is i start working on it.

**Comment by iamareebjamal** [comment]
Not a priority

**Comment by jyotijauhari** [comment]
> **Describe the chore**
> There are various hardcoded strings present in the code which can be replaced.
> 
> **Would you like to work on the issue?**
> 
> * [x]  Yes
> * [ ]  No
> * Other:

@dheerajkotwani  I want to work on this issue,  can you assign this issue to me?

**Comment by iamareebjamal** [comment]
> Not a priority

**Comment by kusoz5** [comment]
can i work over this issue?

**Comment by ghost** [comment]
hey! Can you pls assign this to me?

**Comment by sambit-sankalp** [comment]
Can I work on this issue?

**Comment by Dev-Akash** [comment]
Do this issue still needs help ?

**Comment by vitika9** [comment]
hey can I please work on this?
