### ISSUE TITLE
No proper indentation given in xml files

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-attendee-android#2620]
**Describe the chore**
While reading the xml files of the project I found that many of them(fragment_order_under_user.xml, fragment_sessions.xml, etc) don't have proper indentation or don't go according to the guideines 

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by dheerajkotwani** [comment]
@liveHarshit do this needs to modified?

**Comment by Rita-Okonkwo** [comment]
Hello please has this been taken care of?

**Comment by pratyaksh1610** [comment]
@nikit19  I would like to work on this issue.

Thankyou
Pratyaksh
