### ISSUE TITLE
bug: multi line input and alignment of apply coupons

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-attendee-android#2621]
**Describe the bug**
The alignment of the apply coupons Edit text is not proper also there is multi line input for it.

**To Reproduce**
1. Go to Tickets
2. Click on apply coupons
3. Input multi line text

**Expected behavior**
The text must be single line as all promo codes or discount coupons are single line text. Also the editText and button must be aligned properly

**Screenshots**
![Screenshot_2020-02-01-12-33-06-525_com eventyay attendee](https://user-images.githubusercontent.com/44086235/73588535-696fdd00-44f0-11ea-9131-3593b0030273.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|
|Android Version|Nougat 7.0 |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by Dhruv-194** [comment]
I'm new to open source but I can definitely contribute to this issue. Please assign me this issue.

**Comment by iamareebjamal** [comment]
Please send a PR
