### ISSUE TITLE
bug: No scrolling in past tickets filter

### ISSUE THREAD

**Issue by insaiyancvk** [fossasia/open-event-attendee-android#2628]
**Describe the bug**
There are no scroll bars in the filter in Past Tickets section which makes the layout cut from the bottom while using in landscape mode.

**To Reproduce**
1. Go to Ticket -> Past in landscape mode
2. Click on the Filter button
3. Try to scroll

**Expected behaviour**
It should scroll properly

**Screenshots**
![past_ticket_bug](https://user-images.githubusercontent.com/53230977/73671609-4b150780-46d1-11ea-93bd-6e41402488e7.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Redmi Note 7|
|Android Version| 9(Pie) |

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by dheerajkotwani** [comment]
This issue was fixed with #2608 .Please get the latest commits

**Comment by insaiyancvk** [comment]
@dheerajkotwani If I'm not wrong, you have fixed the scroll view in Tickets filter, not 'Past Ticket' filter

**Comment by dheerajkotwani** [comment]
> 
> @dheerajkotwani If I'm not wrong, you have fixed the scroll view in Tickets filter, not 'Past Ticket' filter

There are no separate files ticket filter and past ticket filter, the issue was resolved for both the cases
