### ISSUE TITLE
Edit Profile Force Close

### ISSUE THREAD

**Issue by wahyuandi840** [fossasia/open-event-attendee-android#2660]
**Describe the bug**
The application force close.

**To Reproduce**
1. Open App
2. Click Profile
3. Click Edit Profile

**Expected behavior**
Show Edit Form. 

**Logs**
java.lang.IllegalStateException: BitmapFactory.decodeByte…g, 0, decodedString.size) must not be null. 

**Screenshots**

**Smartphone Info:**

Device       Xiaomi Note 5A
Android Version Nougat 7.1

**Additional context**
I tried changing the code EditProfileFragment.kt in line 211 from safeArgs.croppedImage.isEmpty () to safeArgs.croppedImage.equals ("''") the error was handled
. 

**Would you like to work on the issue?**

- [ ] Yes
- [x ] No
- Other:

**Comment by ForgottenProgramme** [comment]
Hey, @wahyuandi840 ! I want to work on this issue. 
But I am having trouble setting up the environment. 
I downloaded the apk file. And it runs on the Android Studio emulator but the files in the repository won't open. 
I don't know how to see the source code. 
Would you please help me, @wahyuandi840 ? 


![apk](https://user-images.githubusercontent.com/65779580/82866811-3e017a00-9f47-11ea-9a50-b41ca2a56623.png)

**Comment by iamareebjamal** [comment]
You don't see source code by installing APK, you see it by cloning the repo https://github.com/fossasia/open-event-attendee-android

<blockquote><img src="https://avatars1.githubusercontent.com/u/6295529?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/fossasia/open-event-attendee-android">fossasia/open-event-attendee-android</a></strong></div><div>Open Event Attendee Android General App https://github.com/fossasia/open-event-android/blob/apk/open-event-dev-app-playStore-debug.apk - fossasia/open-event-attendee-android</div></blockquote>

**Comment by devptyagi** [comment]
is this available?
