### ISSUE TITLE
Integrate Circle CI to automate the APK build

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2768]
Push build script for CircleCI

**Acceptance criteria**
1. Build should trigger for pull requests only
2. Circle CI should build the debug APK only (Fdroid and Play Store)
3. APK link needs to be commented out on the PR itself

**Comment by spacemonkey1101** [comment]
i would like to work on this

**Comment by liveHarshit** [comment]
@spacemonkey1101 Please go ahead

**Comment by VamsiKrishnaCommits** [comment]
Is this open? I would like to work on this.

**Comment by liveHarshit** [comment]
@VamsiKrishnaCommits PR is already raised, please wait.

**Comment by apoorva-raj** [comment]
Hey, Is this still open?
