### ISSUE TITLE
Add a dialog notifying that the app is prototype

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-attendee-android#2793]
Add popup screen: "This mobile app is still in its prototype stage with many features being experimental. We currently recommend using this app only for testing."

The popup should only display once

**Comment by nileshteji** [comment]
@iamareebjamal  This Should be only displayed once on the first time launch of the application ? . I would like to work on this issue.

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by nileshteji** [comment]
@iamareebjamal  
Have Some questions:-
1. When should be the dialog notifying? 
2. Should the dialog be notifyed only once or every time the app is opened(like an onboarding screen)

**Comment by iamareebjamal** [comment]
The popup should only display once on opening of the app
