### ISSUE TITLE
Payment gateway

### ISSUE THREAD

**Issue by VamsiKrishnaCommits** [fossasia/open-event-attendee-android#2821]
**The payment gateway seems to be broken**
 Payment gateway is necessary for a successful booking , I observed that this went missing

**To Reproduce**
Try booking a ticket for an event and you cannot proceed after the payment gateway pops up.
**Expected behavior**
Paypal or other payment modes should work to result a successful transaction 

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | [ Moto E5 Plus] |
|Android Version| [Oreo 8.1]   |

**Would you like to work on the issue?**
 Yes

**Comment by adarsh-dhakad** [comment]
yes want to work
