### ISSUE TITLE
A display bug

### ISSUE THREAD

**Issue by franklinbill** [fossasia/open-event-attendee-android#2824]
**Describe the bug**

Dear developer! In the process of using, I found a bug in layout / display. As shown in the figure, in the start page, text and icons overlap.
App version is 0.9.1, my mobile phone is Google nexus 6, screen resolution setting is 1920*1080, **_font size and display size_** are the largest ! ! !  Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!

**To Reproduce**

**Expected behavior**

We hope to solve the problem of text overlapping

**Logs**

**Screenshots**

![bug-attendee](https://user-images.githubusercontent.com/18572115/103080208-52f2d880-4610-11eb-9b94-3ce43f999fd6.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Google nexus 6|
|Android Version|<Android 8.0|

**Additional context**

**Would you like to work on the issue?**

No

**Comment by varunvjha** [comment]
I want to work on this issue.
