### ISSUE TITLE
A display bug on search

### ISSUE THREAD

**Issue by franklinbill** [fossasia/open-event-attendee-android#2825]
**Describe the bug**

Dear developer! In the process of using, I found a bug in layout / display. As shown in the figure, in the search page, text and image overlap.
App version is 0.9.1, my mobile phone is Google nexus 6, screen resolution setting is 1920*1080, **_font size and display size_** are the largest ! ! ! Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!

**To Reproduce**

**Expected behavior**

We hope to solve the problem of text overlapping

**Logs**

**Screenshots**

![bug-attendee-3](https://user-images.githubusercontent.com/18572115/103080941-dc56da80-4611-11eb-889a-d4d439e6d3a7.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Google nexus 6|
|Android Version|<Android 8.0|

**Additional context**

**Would you like to work on the issue?**

No

**Comment by varunvjha** [comment]
I would like to work on this issue.

**Comment by franklinbill** [comment]
Thank You!

**Comment by Vivek-Prajapatii** [comment]
may i take this issue?
