### ISSUE TITLE
SnackBar showing incomprehensible pop out message in the EventDetails Fragment. 

### ISSUE THREAD

**Issue by VamsiKrishnaCommits** [fossasia/open-event-attendee-android#2832]
**Describe the bug**
The event I clicked was CodeHeat Ask me Anything January , somehow it failed to fetch something and popped out the below snack bar which does not make sense
**To Reproduce**
Click on the event CodeHeat AMA- January edition

**Expected behavior**
A sensible message 

**Screenshots**

![Screenshot_20210119-211156_Eventyay Attendee](https://user-images.githubusercontent.com/59550525/105211474-4e1f3700-5b72-11eb-8ebc-1e4b0e032600.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung  J7 duo|
|Android Version| Oreo  |

**Would you like to work on the issue?**
- [.] Yes

**Comment by saurabhraj042** [comment]
I would like to work on this issue.

**Comment by Vivek-Prajapatii** [comment]
@VamsiKrishnaCommits  may i take this issue ?
and kindly help me to solve this issue please
