### ISSUE TITLE
Update APK generation and follow name conventions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-attendee-android#658]
Please reduce the number of APKs and change the name as follows:

- eventyay-attendee-dev-debug.apk
- eventyay-attendee-dev-debug-fdroid.apk
- eventyay-attendee-master-debug.apk
- eventyay-attendee-master-debug-fdroid.apk
- eventyay-attendee-master-unsigned.apk
- eventyay-attendee-master-unsigned-fdroid.apk

![screenshot from 2018-10-26 10-33-18](https://user-images.githubusercontent.com/1583873/47554831-90f9f200-d90a-11e8-8707-111ad13c3f8e.png)

**Comment by iamareebjamal** [comment]
Duplicate of #378

**Comment by liveHarshit** [comment]
@iamareebjamal Will replacing it
```
if [ "$TRAVIS_BRANCH" == "$DEPLOY_BRANCH" ]; then
	for file in app*; do
		if [[ $file = "open-event"* ]]; then
			continue
		fi
		mv $file open-event-dev-${file%%}
	done
fi
```
with

```
if [ "$TRAVIS_BRANCH" == "$DEPLOY_BRANCH" ]; then
    for file in app*; do
          mv $file open-event-dev-${file%%}
    done
fi
```
solve the issue?

**Comment by iamareebjamal** [comment]
No
