### ISSUE TITLE
Implement pagination in the app

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-attendee-android#84]
Working on it

**Comment by nikit19** [comment]
@iamareebjamal I am having lots of issues in implementing this. I thought of using this library as it was recommended in Jetpack. https://developer.android.com/topic/libraries/architecture/paging/ I was going through the documentation and I understand how everything works but I am not able to implement it in the app. The documentation mentions a function called `requestAndSaveData()` in `BoundaryCallback`
This function is used when the person reaches the end of the list and needs a GET request from the server with page no. argument incremented. This is one  of the places where I am stuck as I am not able to replicate this function in the app. 
There some parts which I have implemented but I am still not sure whether I am implementing it correctly or not. I am returning `RxPagedListBuilder` from the `getEvents()` method in the `EventService` class
Could you please help.
Thank you

**Comment by iamareebjamal** [comment]
Please push the WIP PR

**Comment by theLimitBreaker** [comment]
Does the Server provide the data in Pages , I mean does server it self has pages ?

**Comment by iamareebjamal** [comment]
Study the API please. It's already available in API docs what's present and what not

**Comment by aggarwalpulkit596** [comment]
@nikit19 can I start working on this?

**Comment by nikit19** [comment]
Please go ahead.
